<a href="https://colab.research.google.com/github/SouravDasz/Deep-learning-projects-models-only-/blob/main/attention_mechanism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import torch
from torch.utils.data import Dataset,DataLoader
import torch.nn as nn
import torch.optim as optim

In [2]:
df=pd.read_csv("/content/english_to_bangla (1).csv")

In [3]:
df.head()

,en,bn
0,a child in a pink dress is climbing up a set o...,একটি গোলাপী জামা পরা বাচ্চা মেয়ে একটি বাড়ির প্...
1,a girl going into a wooden building .,একটি মেয়ে শিশু একটি কাঠের বাড়িতে ঢুকছে
2,a little girl climbing into a wooden playhouse .,একটি বাচ্চা তার কাঠের খেলাঘরে উঠছে ।
3,a little girl climbing the stairs to her playh...,ছোট মেয়েটি তার খেলার ঘরের সিড়ি বেয়ে উঠছে
4,a little girl in a pink dress going into a woo...,গোলাপি জামা পড়া ছোট একটি মেয়ে একটি কাঠের তৈরি...

In [4]:
df["en"][100]

'two different breeds of brown and white dogs play on the beach .'

In [5]:
import re

In [6]:
def tokenizing(x):
  x=x.lower()
  x=re.sub("[^a-zA-Z]"," ",x)
  x=x.split()
  return x

In [7]:
df["en"]=df["en"].apply(tokenizing)

In [8]:
df["en"][5]

['a', 'black', 'dog', 'and', 'a', 'spotted', 'dog', 'are', 'fighting']

In [9]:
import re

def tokenizing_bn(x):
    x = x.lower()
    x = re.sub(r"[^\u0980-\u09FF]+", " ", x)
    x = x.split()
    return x

In [10]:
df["bn"]=df["bn"].apply(tokenizing_bn)

In [11]:
df

,en,bn
0,"[a, child, in, a, pink, dress, is, climbing, u...","[একটি, গোলাপী, জামা, পরা, বাচ্চা, মেয়ে, একটি, ..."
1,"[a, girl, going, into, a, wooden, building]","[একটি, মেয়ে, শিশু, একটি, কাঠের, বাড়িতে, ঢুকছে]"
2,"[a, little, girl, climbing, into, a, wooden, p...","[একটি, বাচ্চা, তার, কাঠের, খেলাঘরে, উঠছে]"
3,"[a, little, girl, climbing, the, stairs, to, h...","[ছোট, মেয়েটি, তার, খেলার, ঘরের, সিড়ি, বেয়ে, উঠছে]"
4,"[a, little, girl, in, a, pink, dress, going, i...","[গোলাপি, জামা, পড়া, ছোট, একটি, মেয়ে, একটি, কা..."
...,...,...
39060,"[a, man, in, a, pink, shirt, climbs, a, rock, ...","[গোলাপী, শার্টের, একটি, লোক, একটি, শিলার, উপরে..."
39061,"[a, man, is, rock, climbing, high, in, the, air]","[একজন, মানুষ, পাথরে, চড়ছে, অনেক, উপরে]"
39062,"[a, person, in, a, red, shirt, climbing, up, a...","[লাল, শার্টের, একজন, ব্যক্তি, সহায়তার, হাতলগু..."
39063,"[a, rock, climber, in, a, red, shirt]","[লাল, শার্টে, একটি, রক, আরোহী]"
39064,"[a, rock, climber, practices, on, a, rock, cli...","[একটি, রক, আরোহী, একটি, শৈল, আরোহণ, প্রাচীর, এ..."

In [12]:
df["bn"][1]

['একটি', 'মেয়ে', 'শিশু', 'একটি', 'কাঠের', 'বাড়িতে', 'ঢুকছে']

# Integer Encoding

In [13]:
from collections import Counter

In [14]:
en_vocab={
    "<oov>":0,
}
bn_vocab={
    "<oov>":0,
    "<sos>":1,
    "<eos>":2
}

In [15]:
en_counter=Counter()
bn_counter=Counter()

In [16]:
for sentence in df["en"]:
  en_counter.update(sentence)

In [17]:
en_counter

Counter({'a': 61112,
         'child': 1532,
         'in': 18406,
         'pink': 732,
         'dress': 347,
         'is': 9039,
         'climbing': 478,
         'up': 1273,
         'set': 109,
         'of': 6590,
         'stairs': 106,
         'an': 2393,
         'entry': 1,
         'way': 53,
         'girl': 3295,
         'going': 143,
         'into': 1045,
         'wooden': 272,
         'building': 504,
         'little': 1748,
         'playhouse': 6,
         'the': 17672,
         'to': 3113,
         'her': 1169,
         'cabin': 4,
         'black': 3659,
         'dog': 7596,
         'and': 8634,
         'spotted': 37,
         'are': 3412,
         'fighting': 123,
         'tri': 14,
         'colored': 216,
         'playing': 1896,
         'with': 7559,
         'each': 408,
         'other': 744,
         'on': 10433,
         'road': 389,
         'white': 3797,
         'brown': 2449,
         'spots': 28,
         'staring': 57,
         'at': 2869,
         'street': 939,
         'two': 5427,
         'dogs': 1924,
         'different': 45,
         'breeds': 5,
         'looking': 735,
         'pavement': 46,
         'moving': 41,
         'toward': 142,
         'covered': 358,
         'paint': 62,
         'sits': 575,
         'front': 1366,
         'painted': 64,
         'rainbow': 22,
         'hands': 242,
         'bowl': 30,
         'sitting': 1359,
         'large': 1189,
         'small': 1243,
         'grass': 1490,
         'plays': 508,
         'fingerpaints': 3,
         'canvas': 6,
         'it': 393,
         'there': 299,
         'pigtails': 14,
         'painting': 43,
         'young': 2601,
         'outside': 779,
         'man': 7109,
         'lays': 55,
         'bench': 371,
         'while': 1919,
         'his': 2273,
         'by': 1221,
         'him': 387,
         'which': 49,
         'also': 19,
         'tied': 15,
         'sleeping': 60,
         'next': 743,
         'shirtless': 99,
         'lies': 43,
         'park': 491,
         'laying': 187,
         'holding': 1307,
         'leash': 128,
         'ground': 346,
         'orange': 732,
         'hat': 676,
         'starring': 7,
         'something': 340,
         'wears': 114,
         'glasses': 202,
         'gauges': 2,
         'wearing': 3011,
         'blitz': 1,
         'beer': 44,
         'can': 39,
         'crocheted': 1,
         'pierced': 6,
         'ears': 63,
         'rope': 243,
         'net': 56,
         'red': 2643,
         'roping': 2,
         'climbs': 198,
         'bridge': 141,
         'grips': 2,
         'onto': 208,
         'ropes': 38,
         'playground': 195,
         'running': 1901,
         'grassy': 448,
         'garden': 54,
         'surrounded': 174,
         'fence': 324,
         'through': 1883,
         'boston': 9,
         'terrier': 31,
         'lush': 8,
         'green': 1210,
         'runs': 852,
         'near': 997,
         'shakes': 35,
         'its': 870,
         'head': 371,
         'shore': 164,
         'ball': 1714,
         'edge': 165,
         'beach': 1014,
         'feet': 87,
         'stands': 854,
         'shaking': 67,
         'off': 735,
         'water': 2670,
         'standing': 1770,
         'turned': 20,
         'one': 1183,
         'side': 293,
         'boy': 3533,
         'smiles': 190,
         'stony': 3,
         'wall': 539,
         'city': 311,
         'overalls': 24,
         'working': 24,
         'stone': 127,
         'aross': 1,
         'walking': 1132,
         'paved': 42,
         'metal': 114,
         'pole': 156,
         'behind': 622,
         'smiling': 461,
         'shirt': 1934,
         'blue': 2238,
         'jeans': 220,
         'rock': 724,
         'leaps': 188,
         'over': 1341,
         'log': 55,
         'grey': 244,
         'leaping': 132,
         'fallen': 69,
         'tree': 422,
         'mottled': 2,
         'collar': 191,
         'jumping': 1414,
         'jumped': 31,
         'stump': 27,
         'snow': 1421,
         'field': 1206,
         'surface': 64,
         'displaying': 5,
         'pictures': 67,
         'skier': 166,
         'skis': 74,
         'past': 147,
         'another': 932,
         'paintings': 5,
         'person': 1487,
         'framed': 7,
         'looks': 502,
         'trees': 252,
         'artwork': 4,
         'for': 927,
         'sale': 7,
         'collage': 2,
         'cliff': 188,
         'group': 1202,
         'people': 2856,
         'belays': 1,
         'seven': 29,
         'climbers': 27,
         'ascending': 7,
         'face': 475,
         'whilst': 147,
         'several': 306,
         'row': 34,
         'watches': 273,
         'holds': 463,
         'line': 148,
         'chases': 93,
         'from': 901,
         'sprinkler': 51,
         'lawn': 112,
         'hose': 45,
         'away': 166,
         'prepares': 48,
         'catch': 354,
         'thrown': 44,
         'object': 149,
         'nearby': 148,
         'cars': 63,
         'about': 147,
         'yellow': 1181,
         'mouth': 921,
         'toy': 560,
         'ready': 122,
         'flying': 162,
         'air': 1002,
         'after': 178,
         'get': 107,
         'jumps': 928,
         'towards': 243,
         'trying': 158,
         'midair': 197,
         'woman': 3372,
         'waters': 28,
         'big': 269,
         'lake': 323,
         'lone': 76,
         'duck': 37,
         'swimming': 429,
         'around': 631,
         'watching': 248,
         'waves': 133,
         'hand': 345,
         'facing': 54,
         'skyline': 14,
         'couple': 245,
         'infant': 15,
         'being': 330,
         'held': 65,
         'male': 109,
         'pond': 95,
         'stroller': 28,
         'sit': 358,
         'baby': 417,
         'their': 681,
         'newborn': 8,
         'under': 245,
         'care': 3,
         'along': 505,
         'body': 183,
         'outdoors': 173,
         'surf': 75,
         'lab': 22,
         'tags': 6,
         'frolicks': 2,
         'splashes': 67,
         'this': 136,
         'splashing': 126,
         'drilling': 5,
         'hole': 37,
         'ice': 220,
         'frozen': 25,
         'men': 1102,
         'fishing': 107,
         'play': 703,
         'making': 151,
         'turn': 66,
         'soft': 13,
         'sand': 460,
         'together': 400,
         'tan': 372,
         'sandy': 111,
         'uses': 26,
         'picks': 12,
         'crampons': 1,
         'scale': 1,
         'climber': 118,
         'jacket': 666,
         'pants': 249,
         'scaling': 20,
         'waterfall': 85,
         'carries': 118,
         'as': 849,
         'he': 201,
         'walks': 546,
         'carrying': 430,
         'has': 545,
         'item': 19,
         'wet': 176,
         'kayak': 87,
         'life': 85,
         'jackets': 67,
         'rowing': 35,
         'canoe': 71,
         'gentle': 1,
         'ride': 250,
         'courtyard': 28,
         'catching': 100,
         'snaps': 1,
         'lunges': 6,
         'chocolate': 14,
         'too': 8,
         'late': 3,
         'captures': 1,
         'driveway': 15,
         'stick': 438,
         'kneeling': 34,
         'goalie': 41,
         'hockey': 185,
         'guarding': 9,
         'goal': 83,
         'kid': 179,
         'rink': 30,
         'right': 92,
         'crouches': 30,
         'modern': 5,
         'art': 40,
         'structure': 76,
         'glass': 61,
         'reads': 46,
         'newspaper': 38,
         'sculpture': 21,
         'office': 12,
         'statue': 63,
         'backpack': 158,
         'buildings': 69,
         'reading': 96,
         'tent': 84,
         'enter': 8,
         'setting': 81,
         'hut': 12,
         'iced': 3,
         'tarp': 8,
         'snowy': 403,
         'three': 1352,
         'hill': 424,
         'sky': 146,
         'them': 257,
         'stand': 515,
         'kneels': 25,
         'skyscraper': 6,
         'very': 157,
         'tall': 143,
         'distance': 107,
         'camera': 690,
         'bites': 31,
         'hard': 19,
         'treat': 16,
         'biting': 77,
         'baked': 2,
         'good': 6,
         'putting': 34,
         'both': 82,
         'eats': 52,
         'food': 93,
         'table': 255,
         'eating': 144,
         'pizza': 10,
         'tin': 1,
         'dish': 11,
         'mountainside': 24,
         'check': 7,
         'out': 741,
         'view': 82,
         'hilltop': 2,
         'overlooking': 102,
         'valley': 23,
         'hang': 33,
         'top': 482,
         'overlook': 6,
         'rest': 24,
         'ledge': 75,
         'above': 220,
         'moutains': 1,
         'down': 1792,
         'many': 183,
         'inflatable': 73,
         'boats': 41,
         'kayakers': 8,
         'railing': 110,
         'rafts': 6,
         'below': 54,
         'crowd': 520,
         'jersey': 111,
         'pose': 209,
         'some': 610,
         'multiracial': 1,
         'posing': 289,
         'picture': 413,
         'asian': 201,
         'blond': 192,
         'background': 576,
         'guy': 201,
         'striped': 214,
         'takeout': 1,
         'television': 9,
         'floor': 153,
         'fast': 48,
         'meal': 14,
         'someone': 154,
         'tv': 13,
         'teens': 7,
         'rail': 93,
         'crowded': 77,
         'takes': 166,
         'jump': 382,
         'skateboard': 405,
         'performing': 181,
         'trick': 344,
         'leans': 57,
         'skateboarder': 275,
         'doing': 404,
         'board': 135,
         'platform': 48,
         'skateboarders': 11,
         'paddling': 47,
         'river': 232,
         'seen': 40,
         'kayaking': 27,
         'paddles': 33,
         'boat': 273,
         'paddle': 39,
         'shallow': 126,
         'girls': 834,
         'ocean': 454,
         'four': 495,
         'children': 1141,
         'pajamas': 18,
         'have': 74,
         'pillow': 16,
         'fight': 74,
         'kids': 337,
         'bed': 157,
         'having': 48,
         'constructions': 1,
         'workers': 18,
         'beam': 21,
         'taking': 204,
         'break': 33,
         'construction': 31,
         'i': 17,
         'take': 77,
         'seat': 50,
         'steel': 4,
         'boys': 655,
         'puddle': 90,
         'balloon': 43,
         'mud': 112,
         'sunny': 66,
         'day': 138,
         'appears': 36,
         'wait': 43,
         'hailing': 1,
         'taxi': 4,
         'signaling': 1,
         'traffic': 47,
         'blonde': 199,
         'hair': 412,
         'tube': 58,
         'waving': 52,
         'arm': 145,
         'oncoming': 2,
         'brochure': 2,
         'train': 107,
         'rides': 432,
         'magizine': 1,
         'book': 77,
         'pamphlet': 1,
         'rocky': 237,
         'run': 336,
         'across': 449,
         'stones': 9,
         'area': 385,
         'descends': 11,
         'end': 51,
         'high': 282,
         'diving': 73,
         'pool': 684,
         'dive': 11,
         'window': 136,
         'overshirt': 1,
         'tank': 77,
         'chrome': 1,
         'door': 61,
         'puts': 34,
         'elevator': 7,
         'light': 164,
         'swim': 95,
         'shorts': 375,
         'trunks': 94,
         'arms': 238,
         'outstretched': 38,
         'hiker': 77,
         'bluff': 5,
         'mountains': 203,
         'ski': 97,
         's': 402,
         'landscape': 43,
         'mountain': 527,
         'beautiful': 53,
         'pauses': 10,
         'mountaintop': 24,
         'attempting': 53,
         'purple': 306,
         'low': 66,
         'cut': 31,
         'yard': 192,
         'frisbee': 321,
         'parking': 69,
         'lot': 105,
         'middle': 160,
         'during': 171,
         'heavy': 28,
         'mat': 22,
         'between': 123,
         'suv': 14,
         'pickup': 4,
         'open': 187,
         'busy': 100,
         'terrain': 36,
         'woolly': 1,
         'doberman': 16,
         'chasing': 179,
         'catches': 114,
         'tennis': 408,
         'multicolor': 11,
         'balloons': 28,
         'night': 155,
         'hot': 29,
         'lit': 50,
         'lined': 42,
         'nighttime': 12,
         'helmet': 350,
         'bike': 828,
         'miniature': 5,
         'dirt': 565,
         'bicycle': 397,
         'race': 362,
         'pedals': 3,
         'quickly': 29,
         'bmx': 68,
         'eight': 17,
         'gathered': 67,
         'dark': 263,
         'porch': 24,
         'darkened': 10,
         'room': 131,
         'throwing': 106,
         'cleans': 2,
         'bubbles': 88,
         'suds': 4,
         'wiped': 2,
         'clean': 7,
         'foam': 19,
         'ramp': 288,
         'soapy': 1,
         'getting': 121,
         'cleaned': 1,
         'slides': 91,
         'slide': 299,
         'wading': 56,
         'toys': 49,
         'floating': 37,
         'backyard': 66,
         'sliding': 119,
         'colorful': 217,
         'tubes': 2,
         'falling': 78,
         'wetsuit': 72,
         'toddler': 168,
         'waiting': 117,
         'come': 11,
         'so': 16,
         'droplets': 7,
         'fly': 38,
         'throws': 66,
         'sticks': 62,
         'tongue': 106,
         'make': 61,
         'faces': 73,
         'sticking': 51,
         'look': 258,
         'silly': 17,
         'horse': 232,
         'sweatshirt': 73,
         'fire': 109,
         'barrel': 20,
         'lead': 17,
         'horses': 90,
         'contained': 1,
         'bulldog': 8,
         'sheep': 55,
         'boxer': 18,
         'pushing': 64,
         'anouther': 1,
         'skinny': 17,
         'smaller': 62,
         'int': 6,
         'various': 19,
         'sizes': 4,
         'lady': 220,
         'no': 87,
         'dock': 91,
         'deck': 38,
         'closeup': 65,
         'that': 391,
         'paws': 29,
         'lying': 97,
         'resting': 43,
         'tiled': 9,
         'eyes': 92,
         'rests': 23,
         'patio': 21,
         'bricks': 5,
         'artificial': 10,
         'safety': 31,
         'harness': 80,
         'indoor': 42,
         'rocks': 252,
         'ring': 68,
         'jumphouse': 1,
         'teenage': 71,
         'seating': 7,
         'inflated': 5,
         'family': 86,
         'tractor': 10,
         'polaris': 3,
         'vehicle': 79,
         'played': 19,
         'wheeler': 19,
         'riding': 870,
         'atv': 37,
         'costume': 132,
         'left': 89,
         'sequined': 4,
         'feather': 12,
         'sidewalk': 369,
         'salmon': 2,
         'bikini': 66,
         'outfit': 159,
         'drinking': 100,
         'pop': 7,
         'approached': 2,
         'flamboyant': 3,
         'dressed': 568,
         'feathered': 8,
         'headress': 1,
         'skiiers': 8,
         'forest': 154,
         'skiing': 106,
         'wooded': 97,
         'cross': 73,
         'country': 36,
         'skiers': 35,
         'woodland': 18,
         'trail': 143,
         'woods': 200,
         'hikers': 34,
         'pathway': 12,
         'path': 320,
         'happily': 25,
         'energetic': 1,
         'mother': 43,
         'boardwalk': 24,
         'sea': 29,
         'pier': 34,
         'evening': 9,
         'pony': 13,
         'wintertime': 2,
         'atop': 37,
         'draft': 3,
         'n': 7,
         'daft': 1,
         'pull': 31,
         'cart': 88,
         'golden': 104,
         'sleigh': 4,
         'driven': 10,
         'coat': 267,
         'pulling': 106,
         'carriage': 19,
         'sled': 116,
         'steered': 2,
         'sheer': 16,
         'using': 62,
         'flat': 13,
         'rappels': 2,
         'steep': 58,
         'incline': 10,
         'vest': 97,
         'inside': 172,
         'dome': 3,
         'shaft': 2,
         'cave': 21,
         'shows': 32,
         'spelunkers': 2,
         'cavern': 1,
         'bathed': 1,
         'sunlight': 11,
         'backpackers': 2,
         'lay': 23,
         'dry': 76,
         'camp': 6,
         'gear': 113,
         'chalk': 17,
         'portrait': 7,
         'stream': 111,
         'drawing': 12,
         'barn': 13,
         'like': 102,
         'elaborate': 11,
         'illustration': 2,
         'deep': 86,
         'pile': 74,
         'fountain': 179,
         'fountains': 14,
         'sprayed': 25,
         'corgi': 7,
         'tunnel': 67,
         'course': 122,
         'obstacle': 113,
         'obedience': 3,
         'swimsuit': 60,
         'handrail': 32,
         'bathing': 118,
         'suit': 247,
         'spray': 37,
         'soaked': 12,
         'jet': 23,
         'shower': 20,
         'gets': 103,
         'underwater': 53,
         'headed': 16,
         'swims': 95,
         'gun': 41,
         'foot': 44,
         'aims': 5,
         'fireplace': 11,
         'new': 17,
         'pointed': 13,
         'alone': 33,
         'jagged': 7,
         'snowmobile': 11,
         'mid': 29,
         'snowmobiler': 2,
         'flies': 96,
         'rider': 178,
         'or': 85,
         'machine': 31,
         'pine': 22,
         'rural': 44,
         'snowmobiles': 4,
         'helmets': 39,
         'goggles': 73,
         'snowmobiling': 2,
         'helmeted': 15,
         'drive': 15,
         'atvs': 3,
         'heads': 48,
         'wheel': 63,
         'wheelers': 3,
         'empty': 50,
         'all': 138,
         'gin': 1,
         'airborne': 74,
         'quad': 6,
         'harvested': 2,
         'cornfield': 1,
         'happy': 20,
         'od': 1,
         'playfully': 31,
         'soccer': 559,
         'tucked': 1,
         't': 166,
         'artist': 14,
         'paints': 12,
         'clouds': 32,
         'braids': 6,
         'colors': 22,
         'paper': 79,
         'cyclist': 66,
         'curved': 4,
         'aerodynamic': 2,
         'sharp': 18,
         'curve': 22,
         'pedaling': 3,
         'cows': 13,
         'graze': 2,
         'biker': 159,
         'fetch': 31,
         'pounces': 8,
         'cine': 1,
         'old': 174,
         'fashioned': 8,
         'video': 39,
         'steadies': 2,
         'aim': 4,
         'rosy': 1,
         'cheeks': 6,
         'lips': 17,
         'border': 9,
         'collie': 29,
         'audience': 37,
         'dug': 3,
         'watch': 235,
         'agile': 1,
         'onlookers': 50,
         'closely': 5,
         'smooth': 6,
         'stacking': 1,
         'against': 197,
         'backdrop': 9,
         'shoes': 90,
         'rappeling': 1,
         'headlamp': 2,
         'attached': 53,
         'snakeskin': 1,
         'sprays': 11,
         'frog': 5,
         'public': 47,
         'wood': 70,
         'barrior': 1,
         'animal': 96,
         'bird': 189,
         'seeds': 6,
         'sunflower': 1,
         'clinging': 5,
         'finger': 36,
         'wades': 12,
         'guided': 3,
         'laughs': 32,
         'playful': 7,
         'beige': 51,
         'torwards': 1,
         'outdoor': 134,
         'handstand': 48,
         'does': 217,
         'sheets': 5,
         'upside': 104,
         'snowboard': 80,
         'surfboard': 133,
         'bikes': 86,
         'traveling': 15,
         'worn': 5,
         'motorcycles': 26,
         'motorbikes': 7,
         'follow': 13,
         'garment': 2,
         'flag': 98,
         'crescent': 1,
         'moon': 5,
         'star': 13,
         'gown': 9,
         'muslim': 3,
         'helps': 29,
         'wave': 273,
         'half': 40,
         'naked': 52,
         'chair': 132,

In [18]:
for sentence in df["bn"]:
  bn_counter.update(sentence)

In [19]:
bn_counter

Counter({'একটি': 23972,
         'গোলাপী': 308,
         'জামা': 1368,
         'পরা': 2286,
         'বাচ্চা': 1684,
         'মেয়ে': 1453,
         'বাড়ির': 15,
         'প্রবেশ': 24,
         'পথের': 41,
         'সিঁড়ি': 29,
         'বেয়ে': 282,
         'উঠছে': 376,
         'শিশু': 1484,
         'কাঠের': 395,
         'বাড়িতে': 1,
         'ঢুকছে': 5,
         'তার': 2340,
         'খেলাঘরে': 5,
         'ছোট': 2245,
         'মেয়েটি': 460,
         'খেলার': 355,
         'ঘরের': 99,
         'সিড়ি': 11,
         'গোলাপি': 319,
         'পড়া': 672,
         'তৈরি': 158,
         'ঘরে': 70,
         'করছে': 4477,
         'কালো': 3225,
         'কুকুর': 7248,
         'এবং': 4414,
         'ছোপওয়ালা': 13,
         'ঝগড়া': 17,
         'তিন': 304,
         'রঙা': 8,
         'কুকুরের': 630,
         'সাথে': 1225,
         'রাস্তায়': 568,
         'খেলছে': 2338,
         'ও': 1869,
         'সাদা': 3254,
         'বাদামি': 767,
         'ছোপযুক্ত': 58,
         'রাস্তায়': 604,
         'একে': 287,
         'অপরের': 178,
         'দিকে': 1545,
         'তাকিয়ে': 341,
         'আছে': 6266,
         'ভিন্ন': 57,
         'জাতের': 68,
         'দুটি': 2356,
         'রাস্তার': 244,
         'পাশে': 1653,
         'দুইটি': 377,
         'পরস্পরের': 20,
         'এগিয়ে': 80,
         'যাচ্ছ': 3,
         'রঙে': 12,
         'মাখা': 5,
         'হাতে': 787,
         'রঙের': 2308,
         'বাটিতে': 2,
         'হাত': 592,
         'দিয়ে': 2096,
         'রঙ': 56,
         'আঁকা': 68,
         'রংধনুর': 7,
         'সামনে': 1533,
         'বসে': 2574,
         'ছোটো': 195,
         'মেয়ে': 1140,
         'ঘাসে': 395,
         'আঙুলে': 6,
         'রং': 58,
         'নিয়ে': 1576,
         'খেলা': 415,
         'রংধনু': 10,
         'ক্যানভসের': 1,
         'চুলে': 39,
         'বেণী': 12,
         'করা': 345,
         'চিত্রের': 17,
         'বেনী': 4,
         'অল্প': 155,
         'বয়সী': 10,
         'বাইরে': 745,
         'ঘাসের': 1153,
         'উপর': 3099,
         'একজন': 7928,
         'পুরুষ': 633,
         'টেবিলের': 79,
         'শুয়ে': 165,
         'যখন': 421,
         'মানুষ': 832,
         'বেঞ্চিতে': 6,
         'শুয়ে': 225,
         'যার': 265,
         'কুকুরও': 4,
         'বাধা': 153,
         'ব্যক্তি': 1664,
         'বেঞ্চে': 242,
         'ঘুমাচ্ছে': 44,
         'নগ্নদেহী': 1,
         'লোক': 5897,
         'পোষা': 37,
         'কুকুরকে': 201,
         'বাগানে': 38,
         'লম্বা': 314,
         'আসনে': 53,
         'মাটিতে': 209,
         'থাকা': 672,
         'কুকুরটির': 77,
         'শিকল': 48,
         'ধরে': 1513,
         'লোকটি': 814,
         'কমলা': 618,
         'টুপি': 749,
         'পরিহিত': 1940,
         'কোনোকিছুর': 1,
         'পরেছ': 1,
         'চশমাও': 1,
         'পরেছে': 72,
         'চশমাযুক্ত': 14,
         'ব্লিটজ': 1,
         'পরেছেন': 34,
         'চশমা': 225,
         'বিয়ারের': 6,
         'কৌটা': 1,
         'বানানো': 8,
         'পরে': 1327,
         'কান': 41,
         'ফোঁড়ানো': 1,
         'ব্যক্তিটি': 25,
         'দড়ি': 109,
         'নির্মিত': 13,
         'জালের': 16,
         'লাল': 2312,
         'দড়ি': 96,
         'দড়ির': 30,
         'সেতু': 21,
         'আরোহণ': 220,
         'মাঠে': 968,
         'রশি': 45,
         'আঁকড়ে': 10,
         'বাচ্চাটি': 90,
         'দড়িতে': 18,
         'চড়ে': 275,
         'বেড়ি': 1,
         'যুক্ত': 43,
         'আবৃত': 43,
         'দৌড়াচ্ছে': 528,
         'সাদাকালো': 38,
         'দৌড়াচ্ছে': 1344,
         'বোস্টন': 6,
         'টেরিয়ার': 17,
         'টেরিয়ার': 9,
         'বেড়ার': 100,
         'ঘন': 27,
         'সবুজ': 1017,
         'মধ্যে': 1645,
         'দৌড়ে': 198,
         'যাচ্ছে': 1449,
         'কুকুরটি': 1292,
         'তীরের': 16,
         'কাছে': 484,
         'মাথা': 164,
         'ঝাকাচ্ছে': 5,
         'এর': 462,
         'বল': 1255,
         'সমুদ্রের': 343,
         'পাড়ে': 19,
         'তীরে': 114,
         'দাঁড়িয়ে': 1469,
         'শরীর': 46,
         'থেকে': 1439,
         'জল': 185,
         'ঝেড়ে': 22,
         'ফেলছে': 49,
         'জলের': 320,
         'ধারে': 184,
         'খেলায়': 57,
         'রত': 2,
         'কানওয়ালা': 6,
         'একদিকে': 10,
         'বাঁকিয়ে': 4,
         'পানির': 728,
         'দাড়িয়ে': 554,
         'শহরের': 173,
         'পাথর': 178,
         'দেয়ালের': 54,
         'বালক': 870,
         'হাসছে': 484,
         'ছেলে': 2274,
         'অ্যদিকে': 1,
         'সবর্পরি': 1,
         'কাজ': 62,
         'পাথরের': 470,
         'দেওয়ালের': 40,
         'রাস্তা': 303,
         'পাথুরে': 226,
         'হেঁটে': 404,
         'পেছনে': 297,
         'ধাতব': 85,
         'খাম্বা': 1,
         'রয়েছ': 1,
         'শার্ট': 607,
         'আর': 353,
         'নীল': 1877,
         'জিন্স': 105,
         'পড়া': 220,
         'হাস্যোজ্জ্বল': 31,
         'ছেলেটি': 616,
         'সম্পূর্ণ': 13,
         'উল্টোদিকে': 2,
         'মুখ': 345,
         'করে': 1643,
         'লোকটির': 60,
         'প্রাচীরের': 45,
         'দাঁড়িয়ে': 1631,
         'গাছের': 502,
         'গুঁড়ির': 14,
         'দিয়ে': 1429,
         'লাফ': 1521,
         'দিচ্ছে': 1519,
         'ধূসর': 335,
         'ভেঙে': 12,
         'বড়': 449,
         'পতিত': 16,
         'লাফিয়ে': 150,
         'গলাবন্ধ': 22,
         'পড়ে': 243,
         'কুঁদা': 1,
         'পার': 160,
         'বরফের': 483,
         'মাঝ': 48,
         'উপরে': 717,
         'মাঝে': 170,
         'বাদামী': 1178,
         'বরফে': 431,
         'ঢাকা': 252,
         'মাঠের': 269,
         'শ্বেত': 8,
         'পৃষ্ঠদেশে': 1,
         'বেড়াচ্ছে': 56,
         'আরেকজন': 111,
         'স্কিচালক': 43,
         'কে': 58,
         'কিছু': 1034,
         'ছবি': 645,
         'দেখাচ্ছেন': 21,
         'স্কি': 197,
         'অন্যজন': 35,
         'চিত্র': 27,
         'প্রদর্শন': 77,
         'তুষারে': 164,
         'রাখা': 115,
         'ফ্রেমবন্দি': 1,
         'ছবিগুলো': 1,
         'দেখছে': 781,
         'পাশের': 131,
         'ফ্রেমযুক্ত': 1,
         'করতে': 152,
         'বিক্রয়যোগ্য': 1,
         'চিত্রকর্মগুলোর': 1,
         'তাকিয়ে': 612,
         'ব্যক্তির': 95,
         'কোলাজ': 1,
         'খাড়া': 35,
         'পাহাড়': 125,
         'আরোহন': 17,
         'একদল': 994,
         'পাথুর': 1,
         'উঠার': 51,
         'দেওয়ালে': 9,
         'শিলায়': 27,
         'চড়ছে': 175,
         'চড়ার': 9,
         'প্রস্তুতি': 57,
         'নিচ্ছে': 233,
         'সাত': 8,
         'পর্বতারোহী': 70,
         'শিলামুখ': 1,
         'আরেক': 98,
         'কয়েকজন': 49,
         'আরোহী': 163,
         'একসাথে': 329,
         'করছেন': 506,
         'পোশাক': 987,
         'নজর': 15,
         'রেখেছে': 223,
         'রশিটি': 1,
         'ঘাসযুক্ত': 115,
         'জায়গার': 13,
         'পানি': 435,
         'ছিটানো': 24,
         'যন্ত্র': 25,
         'ছিটকে': 22,
         'ধরতে': 165,
         'চেষ্টা': 490,
         'বদামী': 1,
         'জলসেচনের': 3,
         'পাইপের': 16,
         'লনে': 42,
         'দেওয়ার': 35,
         'নলের': 16,
         'হৌজ': 1,
         'স্প্রিংকলার': 4,
         'পালাচ্ছে': 12,
         'কাছাকাছি': 91,
         'গাড়ি': 173,
         'এমন': 78,
         'ছুঁড়ে': 31,
         'দেয়া': 8,
         'বস্তুটি': 5,
         'ধরার': 365,
         'হলুদ': 1006,
         'খেলনা': 534,
         'চলেছে': 319,
         'উড়তে': 3,
         'জন্য': 1021,
         'প্রস্তুত': 102,
         'বলের': 242,
         'পিছনে': 580,
         'শূণ্যে': 37,
         'লাফাচ্ছে': 424,
         'খেলনার': 64,
         'দিলো': 313,
         'লাফালাফি': 47,
         'শুন্যে': 18,
         'নিয়ে': 1176,
         'শহরে': 48,
         'মহিলা': 2753,
         'কিনারায়': 43,
         'বড়': 384,
         'হ্রদের': 93,
         'কিনারায়': 36,
         'একা': 69,
         'হাঁস': 33,
         'হ্রদে': 56,
         'সাঁতার': 338,
         'কাটছে': 275,
         'দীঘির': 14,
         'উদ্যান': 2,
         'ঘেরা': 131,
         'পানিতে': 1074,
         'হাঁসের': 19,
         'তরুণ': 257,
         'নাড়াচ্ছে': 13,
         'দুইজন': 552,
         'আকাশরেখার': 1,
         'মুখোমুখি': 46,
         'হয়ে': 94,
         'পুকুরের': 62,
         'ঘোরানোর': 5,
         'এক': 5929,
         'দম্পতি': 224,
         'বাচ্চাটিক্': 1,
         'ঘসের': 10,
         'তাদের': 498,
         'বাচ্চার': 59,
         'বহনকরার': 1,
         'গাড়ী': 91,
         'নবজাতক': 5,
         'শিশুকে': 141,
         'নিচে': 519,
         'আদর': 19,
         'শিশুর': 66,
         'স্ট্রোলারের': 2,
         'গলার': 11,
         'বাধাবুলি': 1,
         'সাগরের': 47,
         'ছিটাচ্ছে': 55,
         'টি': 159,
         'মধ্য': 400,
         'এটি': 38,
         'যা': 144,
         'গর্ত': 24,
         'খুঁড়ছে': 4,
         'জমে': 21,
         'যাওয়া': 32,
         'পুকুরে': 159,
         'ছিদ্র': 4,
         'খুঁড়ছে': 10,
         'জমাট': 4,
         'বাঁধা': 75,
         'আছেন': 867,
         'দুই': 923,
         'জন': 549,
         'মাছ': 144,
         'ধরছে': 188,
         'সমুদ্রতীরে': 35,
         'নরম': 15,
         'বালির': 146,
         'সমুদ্র': 112,
         'সৈকতে': 634,
         'ঘুরছে': 52,
         'সৈকতের': 108,
         'বালুতে': 77,
         'বালুকাময়': 8,
         'তাম্রবর্ণের': 1,
         'একজল': 2,
         'বরফ': 144,
         'বেয়ে': 127,
         'উঠতে': 15,
         'আইস': 43,
         'পিকস': 1,
         'ক্র্যাম্পন': 1,
         'জুতো': 34,
         'ব্যবহার': 54,
         'পাহাড়': 112,
         'বরফারোহী': 1,
         'ঝর্না': 6,
         'গাঁইতি': 2,
         'দেয়ালে': 75,
         'মুখে': 863,
         'জিনিস': 58,
         'রয়েছে': 257,
         'বস্তু': 99,
         'ভেজা': 124,
         'বহন': 184,
         'ক্যানভাসে': 3,
         'মোড়ানো': 9,
         'ছইওয়ালা': 1,
         'সরু': 47,
         'নৌকায়': 56,
         'ভেসে': 54,
         'বেড়াচ্ছে': 38,
         'বহিরাবরণ': 3,
         'ডোঙ্গা': 1,
         'শান্ত': 11,
         'কায়াকিং': 9,
         'নৌকা': 195,
         'বাইছে': 95,
         'ক্যানভাস': 5,
         'মোড়া': 3,
         'ছইওয়ালা': 3,
         'জলাশয়ে': 16,
         'ঘুরে': 60,
         'লাফঝাঁপ': 1,
         'চত্বরে': 3,
         'সম্মুখ': 2,
         'ঝাঁপ': 120,
         'সময়': 200,
         'ফেলে': 68,
         'চকোলেট': 7,
         'ল্যাব': 12,
         'আগেই': 3,
         'ব্ল্যাক': 7,
         'ফেলেছে': 20,
         'লাঠি': 352,
         'গোল': 65,
         'হাঁটু': 58,
         'গেঁড়ে': 4,
         'গোলরক্ষক': 24,
         'হিসেবে': 7,
         'হকি': 171,
         'রিংক': 1,
         'এ': 153,
         'হয়ে': 180,
         'ডান': 33,
         'স্টিক': 11,
         'গোলের': 26,
         'গেড়ে': 14,
         'জ্যাকেট': 531,
         'নত': 11,
         'কাচের': 14,
         'দালানের': 116,
         'আধুনিক': 4,
         'শিল্প': 7,
         'স্থাপত্যের': 6,
         'কার্যালয়ের': 1,
         'ভাস্কর্যেরসামনে': 1,
         'খবরের': 16,
         'কাগজ': 37,
         'পড়ছে': 126,
         'বিশাল': 477,
         'ভাস্কর্যের': 31,
         'অভিমুখে': 4,
         'আছ': 3,
         'ভাষ্কর্য': 1,
         'চত্বরের': 1,
         'থলে': 35,
         'কাঁধে': 93,
         'তাবু': 12,
         'স্থাপন': 10,
         'হচ্ছে': 359,
         'দুজন': 832,
         'শিকার': 7,
         'করার': 283,
         'তাঁবুতে': 14,
         'হিমায়িত': 5,
         'লেকের': 40,
         'ওপর': 112,
         'কুঁড়েঘর': 1,
         'বসাচ্ছে': 5,
         'ত্রিপলের': 1,
         'পৃষ্ঠতলে': 2,
         'তাঁবু': 30,
         'কাঠামোর': 60,
         'দু': 489,
         'তিনটি': 564,
         'কুকুরগুলো': 54,
         'খোলা': 104,
         'আকাশের': 63,
         'ওদের': 1,
         'পাহাড়ের': 194,
         'অবাক': 10,
         'দৃষ্টিতে': 8,
         'ব্যাক্তি': 275,
         'গেড়ে': 35,
         'গগনচুম্বী': 2,
         'ভবনের': 194,
         'অনেক': 240,
         'উঁচু': 110,
         'রয়েছে': 298,
         'আকাশচুম্বি': 1,
         'অট্টালিকা': 1,
         'অতি': 3,
         'উচ্চ': 31,
         'অট্টালিকাটির': 1,
         'তুলতে': 11,
         'চিত্রগাহকের': 1,
         'পিৎজা': 2,
         'খাচ্ছে': 325,
         'শেঁকা': 1,
         'খাবারে': 2,
         'কামড়': 39,
         'একটা': 282,
         'খাবার': 105,
         'টেবিলে': 159,
         'খায়': 29,
         'বালকটি': 119,
         'টিনের': 2,
         'ডিসে': 1,
         'পিজ্জা': 5,
         'কয়েকজন': 205,
         'প্রকৃতিররূপ': 1,
         'পাহাড়চূড়া': 2,
         'তিনজন': 465,
         'উপত্যকা': 7,
         'দর্শন': 3,
         'আড্ডা': 5,
         'উপেক্ষা': 22,
         'পাহাড়ের': 327,
         'বিশ্রাম': 70,
         'ভাসমান': 59,
         'নৌকাসমূহের': 1,
         'কায়াকারদেরকে': 1,
         'অনেকগুলো': 50,
         'ভেলা': 22,
         'নৌকার': 60,
         'জনতাকে': 1,
         'জার্সি': 163,
         'কৌতুহল': 1,
         'নৌকাগুলোর': 2,
         'নারী': 774,
         'তুলছে': 272,
         'অবস্থায়': 56,
         'পেছন': 46,
         'মহিলার': 238,
         'মুখের': 202,
         'সেদিকে': 5,
         'বহু': 21,
         'সংস্কৃত': 1,
         'ছবির': 136,
         'পোজ': 345,
         'দিচ্ছেন': 151,
         'এশিয়ান': 76,
         'স্বর্ণকেশী': 239,
         'পিছনের': 54,
         'তাদেরকে': 9,
         'ডোরাকাটা': 131,
         'জ্যাকেটের': 73,
         'কামরাচ্ছে': 12,
         'টেলিভিশন': 5,
         'কিনে': 3,
         'বাসায়': 3,
         'আনা': 3,
         'মেঝেতে': 107,
         'টিভির': 5,
         'মেয়ের': 76,
         'ভাসছে': 81,
         'টেলিভিশনের': 4,
         'ফাস্ট': 3,
         'ফুড': 4,
         'যুবক': 275,
         'কেউ': 74,
         'হেলান': 58,
         'শৈলশিরার': 4,
         'সমুদ্রসৈকত': 2,
         'পর্যবেক্ষণ': 22,
         'দেয়ালে': 61,
         'কিশোরীরা': 4,
         'বসেছিল': 20,
         'লোকের': 320,
         'ভিড়': 98,
         'তরুণী': 112,
         'জনবহুল': 14,
         'পাটাতনের': 15,
         'স্কেটবোর্ডের': 44,
         'সাহায্যে': 59,
         'সময়': 303,
         'স্কেটবোর্ড': 200,
         'তাকে': 119,
         'কারিকুরি': 3,
         'দেখাচ্ছে': 241,
         'আরেকটি': 138,
         'ঝুঁকে': 43,
         'স্কেটবোর্ডার': 220,
         'চাতুরী': 1,
         'তখন': 39,
         'অন্য': 562,
         'তা': 91,
         'সমতল': 12,
         'স্থানে': 61,
         'খেলোয়াড়': 352,
         'দেখা': 175,
         'বালিকা': 172,
         'দাঁড়ের': 1,
         'নদী': 29,
         'পাড়ি': 8,
         'নদীতে': 98,
         'চালাচ্ছেন': 129,
         'বৈঠা': 38,
         'বৈঠাসহ': 3,
         'কবরী': 2,
         'অগভীর': 96,
         'সমুদ্রপারে': 1,
         'সমুদ্রে': 96,
         'চুল': 155,
         'চার': 146,
         'দল': 226,
         'ঘুমের': 3,
         'পরিধান': 85,
         'বালিশ': 11,
         'যুদ্ধ': 18,
         'বাচ্চাদের': 57,
         'বিছানার': 31,
         'শিশুদের': 32,
         'বাচ্চারা': 178,
         'বালিশের': 5,
         'লড়াই': 35,
         'মিলে': 15,
         'নির্মাণাধীন': 6,
         'কর্মী': 13,
         'কড়িকাঠে': 1,
         'জিরিয়ে': 1,
         'নির্মাণশ্রমিক': 2,
         'নির্মাণ': 10,
         'কড়িকাঠের': 1,
         'শ্রমিক': 16,
         'ইস্পাতের': 2,
         'দন্ডের': 23,
         'বিরতি': 16,
         'নেন': 3,
         'শিশুরা': 125,
         'কর্দমাক্ত': 35,
         'ক্ষুদ্র': 5,
         'ডোবায়': 2,
         'রৌদ্রময়': 3,
         'দিনে': 96,
         'বেলুন': 48,
         'কাদার': 20,
         'খেলে': 90,
         'জলে': 231,
         'সোনালী': 67,
         'চুলের': 246,
         'বাহনের': 1,
         'অপেক্ষা': 172,
         'ট্যাক্সি': 3,
         'থামানোর': 6,
         'ট্র্যাফিক': 6,
         'সিগন্যাল': 1,
         'টপ': 56,
         'নাড়ছেন': 1,
         'পোশাকের': 158,
         'অগ্রসরমান': 2,
         'যানবাহনের': 8,
         'প্রতি': 4,
         'হাতটি': 4,
         'রেখেছেন': 28,
         'ট্রেনে': 31,
         'চড়া': 17,
         'সম্বন্ধীয়': 1,
         'প্রচারপত্র': 4,
         'অল্পবয়সী': 45,
         'ম্যাগাজিন': 12,
         'ভ্রমণরত': 1,
         'ট্রেন': 14,
         'ভ্রমণ': 34,
         'সম্পর্কিত': 3,
         'বই': 76,
         'পড়ছে': 204,
         'সিটে': 25,
         'রেল': 32,
         'পুস্তক': 1,
         'শিশুটি': 164,
         'ভ্রমণের': 5,
         'পাথরে': 140,
         'ধাওয়া': 16,
         'জলাধারের': 3,
         'পশ্চাদপটে': 1,
         'অঞ্চলে': 69,
         'ছুটে': 320,
         'যায়': 179,
         'দেয়ার': 5,
         'জন্যে': 8,
         'ব্যবহৃত': 9,
         'পাটাতন': 4,
         'ডাইভিং': 18,
         'বোর্ড': 63,
         'লাফিয়ে': 317,
         'নিচের': 81,
         'সাঁতারের': 115,
         'পড়লো': 7,
         'স্থান': 28,
         'ঝাঁপিয়ে': 360,
         'পুলের': 124,
         'জানালার': 67,
         'গায়ের': 8,
         'খুলছে': 9,
         'হাতা': 22,
         'কাটা': 51,
         'হলদে': 5,
         'দরজার': 63,
         'লিফটের': 3,
         'নিজের': 66,
         'জামাটি': 2,
         'পরছে': 28,
         'নিচু': 38,
         'উত্তোলক': 1,
         'যন্ত্রের': 18,
         'হালকা': 117,
         'পশমি': 13,
         'তামাটে': 212,
         'বালুময়': 28,
         'চলছে': 320,
         'বিচের': 3,
         'কাটার': 35,
         'পোশাকে': 219,
         'আলোকচিত্রী': 5,
         'কাপড়': 119,
         'পদব্রজে': 20,
         'ভ্রমণকারী': 22,
         'পর্বত': 58,
         'সমূহকে': 1,
         'বরফাবৃত': 18,
         'নিম্নভূমি': 1,
         'তুষার': 181,
         'পর্বতকে': 2,
         'তত্ত্বাবধান': 1,
         'প্রাকৃতিক': 29,
         'দৃশ্য': 77,
         'উপভোগ': 87,
         'স্কাইয়ার': 34,
         'পাহাড়চূড়ায়': 5,
         'থামলেন': 4,
         'কম': 19,
         'ছাটা': 1,
         'উঠানে': 75,
         'বেগুনী': 44,
         'বস্তুকে': 2,
         'খেলনাটি': 5,
         'ফ্রিসবি': 203,
         'পেতে': 14,
         'দেয়': 224,
         'বেগুনি': 185,
         'খেলনাটা': 1,
         'উঠেছে': 67,
         'প্যান্ট': 279,
         'রাখার': 36,
         'ভারী': 23,
         'যানজটের': 1,
         'মাঝখানে': 123,
         'এসইউভি': 6,
         'দরজা': 15,
         'সহ': 313,
         'পিকআপের': 1,
         'মধ্যকার': 4,
         'পার্কিং': 38,
         'মাদুরের': 12,
         'অর্ধনগ্ন': 41,
         'ব্যস্ত': 92,
         'সড়কের': 2,
         'বালিযুক্ত': 1,
         'বিস্তৃত': 10,
         'ভূমিখণ্ডে': 1,
         'ডোবারম্যান': 13,
         'কুকুরটিকে': 60,
         'তাড়া': 141,
         'আকারের': 46,
         'বালুর': 59,
         'অপরকে': 98,
         'ফেললো': 4,
         'টেনিস': 373,
         'বাতাসে': 464,
         'ছুড়ে': 22,
         'দেওয়া': 44,
         'করছিল': 7,
         'রাতের': 99,
         'বেলায়': 3,
         'ফানুস': 2,
         'আকাশে': 48,
         'জ্বলন্ত': 19,
         'লোকেরা': 169,
         'পার্কে': 278,
         'গরম': 29,
         'হাওয়া': 7,
         'ভর্তি': 61,
         'বেলুনগুলি': 1,
         'আকাশযান': 1,
         'রাতে': 62,
         'জনতার': 24,
         'সাতটি': 6,
         'সারিবদ্ধভাবে': 23,
         'হেলমেট': 330,
         'সাইকেল': 725,
         'চালাচ্ছে': 685,
         'ময়লা': 110,
         'চালিয়ে': 22,
         'পাহাড়ি': 12,
         'দিলে': 5,
         'প্রতিযোগিতায়': 39,
         'বাইসাইকেল': 90,
         'ক্ষুদে': 1,
         'প্রতিযোগী': 25,
         'সাইকেলে': 102,
         'দ্রুত': 68,
         'প্যাডেল': 15,
         'আটজন': 6,
         'চতুর্দিকে': 1,
         'জড়ো': 49,
         'হয়েছে': 49,
         'অন্ধকারে': 36,
         'জমায়েত': 3,
         'বারান্দায়': 16,
         'চারপাশে': 165,
         'অন্ধকার': 48,
         'ছোঁড়ার': 3,
         'বিচে': 8,
         'সাবানের': 6,
         'ফেনা': 6,
         'সাফ': 4,
         'মুছিয়ে': 1,
         'নিলো': 11,
         'বুদবুদে': 2,
         'ডেকে': 6,
         'গেছে': 62,
         'ফেনায়': 5,
         'বাজে': 9,
         'ঢালু': 103,
         'পথে': 152,
         'সাবান': 2,
         'পরিষ্কার': 41,
         'সাহায্য': 56,
         'পিছল': 14,
         'পিছলে': 35,
         'খেলনায়': 14,
         'সমৃদ্ধ': 3,
         'কৃত্রিম': 34,
         'বাড়ির': 85,
         'উঠোনে': 87,
         'স্লাইডে': 74,
         'রঙিন': 227,
         'টিউবের': 16,
         'পথ': 99,
         'গড়িয়ে': 19,
         'বেলুনগুলির': 2,
         'স্লাইড': 174,
         'ডুবুরিদের': 2,
         'ডুবুরি': 11,
         'ফেলা': 3,
         'আবার': 7,
         'বাচ্চাকে': 86,
         'শূন্যে': 459,

In [20]:
for word in en_counter:
  if word not in en_vocab:
    en_vocab[word]=len(en_vocab)

In [21]:
en_vocab

{'<oov>': 0,
 'a': 1,
 'child': 2,
 'in': 3,
 'pink': 4,
 'dress': 5,
 'is': 6,
 'climbing': 7,
 'up': 8,
 'set': 9,
 'of': 10,
 'stairs': 11,
 'an': 12,
 'entry': 13,
 'way': 14,
 'girl': 15,
 'going': 16,
 'into': 17,
 'wooden': 18,
 'building': 19,
 'little': 20,
 'playhouse': 21,
 'the': 22,
 'to': 23,
 'her': 24,
 'cabin': 25,
 'black': 26,
 'dog': 27,
 'and': 28,
 'spotted': 29,
 'are': 30,
 'fighting': 31,
 'tri': 32,
 'colored': 33,
 'playing': 34,
 'with': 35,
 'each': 36,
 'other': 37,
 'on': 38,
 'road': 39,
 'white': 40,
 'brown': 41,
 'spots': 42,
 'staring': 43,
 'at': 44,
 'street': 45,
 'two': 46,
 'dogs': 47,
 'different': 48,
 'breeds': 49,
 'looking': 50,
 'pavement': 51,
 'moving': 52,
 'toward': 53,
 'covered': 54,
 'paint': 55,
 'sits': 56,
 'front': 57,
 'painted': 58,
 'rainbow': 59,
 'hands': 60,
 'bowl': 61,
 'sitting': 62,
 'large': 63,
 'small': 64,
 'grass': 65,
 'plays': 66,
 'fingerpaints': 67,
 'canvas': 68,
 'it': 69,
 'there': 70,
 'pigtails': 71,
 'painting': 72,
 'young': 73,
 'outside': 74,
 'man': 75,
 'lays': 76,
 'bench': 77,
 'while': 78,
 'his': 79,
 'by': 80,
 'him': 81,
 'which': 82,
 'also': 83,
 'tied': 84,
 'sleeping': 85,
 'next': 86,
 'shirtless': 87,
 'lies': 88,
 'park': 89,
 'laying': 90,
 'holding': 91,
 'leash': 92,
 'ground': 93,
 'orange': 94,
 'hat': 95,
 'starring': 96,
 'something': 97,
 'wears': 98,
 'glasses': 99,
 'gauges': 100,
 'wearing': 101,
 'blitz': 102,
 'beer': 103,
 'can': 104,
 'crocheted': 105,
 'pierced': 106,
 'ears': 107,
 'rope': 108,
 'net': 109,
 'red': 110,
 'roping': 111,
 'climbs': 112,
 'bridge': 113,
 'grips': 114,
 'onto': 115,
 'ropes': 116,
 'playground': 117,
 'running': 118,
 'grassy': 119,
 'garden': 120,
 'surrounded': 121,
 'fence': 122,
 'through': 123,
 'boston': 124,
 'terrier': 125,
 'lush': 126,
 'green': 127,
 'runs': 128,
 'near': 129,
 'shakes': 130,
 'its': 131,
 'head': 132,
 'shore': 133,
 'ball': 134,
 'edge': 135,
 'beach': 136,
 'feet': 137,
 'stands': 138,
 'shaking': 139,
 'off': 140,
 'water': 141,
 'standing': 142,
 'turned': 143,
 'one': 144,
 'side': 145,
 'boy': 146,
 'smiles': 147,
 'stony': 148,
 'wall': 149,
 'city': 150,
 'overalls': 151,
 'working': 152,
 'stone': 153,
 'aross': 154,
 'walking': 155,
 'paved': 156,
 'metal': 157,
 'pole': 158,
 'behind': 159,
 'smiling': 160,
 'shirt': 161,
 'blue': 162,
 'jeans': 163,
 'rock': 164,
 'leaps': 165,
 'over': 166,
 'log': 167,
 'grey': 168,
 'leaping': 169,
 'fallen': 170,
 'tree': 171,
 'mottled': 172,
 'collar': 173,
 'jumping': 174,
 'jumped': 175,
 'stump': 176,
 'snow': 177,
 'field': 178,
 'surface': 179,
 'displaying': 180,
 'pictures': 181,
 'skier': 182,
 'skis': 183,
 'past': 184,
 'another': 185,
 'paintings': 186,
 'person': 187,
 'framed': 188,
 'looks': 189,
 'trees': 190,
 'artwork': 191,
 'for': 192,
 'sale': 193,
 'collage': 194,
 'cliff': 195,
 'group': 196,
 'people': 197,
 'belays': 198,
 'seven': 199,
 'climbers': 200,
 'ascending': 201,
 'face': 202,
 'whilst': 203,
 'several': 204,
 'row': 205,
 'watches': 206,
 'holds': 207,
 'line': 208,
 'chases': 209,
 'from': 210,
 'sprinkler': 211,
 'lawn': 212,
 'hose': 213,
 'away': 214,
 'prepares': 215,
 'catch': 216,
 'thrown': 217,
 'object': 218,
 'nearby': 219,
 'cars': 220,
 'about': 221,
 'yellow': 222,
 'mouth': 223,
 'toy': 224,
 'ready': 225,
 'flying': 226,
 'air': 227,
 'after': 228,
 'get': 229,
 'jumps': 230,
 'towards': 231,
 'trying': 232,
 'midair': 233,
 'woman': 234,
 'waters': 235,
 'big': 236,
 'lake': 237,
 'lone': 238,
 'duck': 239,
 'swimming': 240,
 'around': 241,
 'watching': 242,
 'waves': 243,
 'hand': 244,
 'facing': 245,
 'skyline': 246,
 'couple': 247,
 'infant': 248,
 'being': 249,
 'held': 250,
 'male': 251,
 'pond': 252,
 'stroller': 253,
 'sit': 254,
 'baby': 255,
 'their': 256,
 'newborn': 257,
 'under': 258,
 'care': 259,
 'along': 260,
 'body': 261,
 'outdoors': 262,
 'surf': 263,
 'lab': 264,
 'tags': 265,
 'frolicks': 266,
 'splashes': 267,
 'this': 268,
 'splashing': 269,
 'drilling': 270,
 'hole': 271,
 'ice': 272,
 'frozen': 273,
 'men': 274,
 'fishing': 275,
 'play': 276,
 'making': 277,
 'turn': 278,
 'soft': 279,
 'sand': 280,
 'together': 281,
 'tan': 282,
 'sandy': 283,
 'uses': 284,
 'picks': 285,
 'crampons': 286,
 'scale': 287,
 'climber': 288,
 'jacket': 289,
 'pants': 290,
 'scaling': 291,
 'waterfall': 292,
 'carries': 293,
 'as': 294,
 'he': 295,
 'walks': 296,
 'carrying': 297,
 'has': 298,
 'item': 299,
 'wet': 300,
 'kayak': 301,
 'life': 302,
 'jackets': 303,
 'rowing': 304,
 'canoe': 305,
 'gentle': 306,
 'ride': 307,
 'courtyard': 308,
 'catching': 309,
 'snaps': 310,
 'lunges': 311,
 'chocolate': 312,
 'too': 313,
 'late': 314,
 'captures': 315,
 'driveway': 316,
 'stick': 317,
 'kneeling': 318,
 'goalie': 319,
 'hockey': 320,
 'guarding': 321,
 'goal': 322,
 'kid': 323,
 'rink': 324,
 'right': 325,
 'crouches': 326,
 'modern': 327,
 'art': 328,
 'structure': 329,
 'glass': 330,
 'reads': 331,
 'newspaper': 332,
 'sculpture': 333,
 'office': 334,
 'statue': 335,
 'backpack': 336,
 'buildings': 337,
 'reading': 338,
 'tent': 339,
 'enter': 340,
 'setting': 341,
 'hut': 342,
 'iced': 343,
 'tarp': 344,
 'snowy': 345,
 'three': 346,
 'hill': 347,
 'sky': 348,
 'them': 349,
 'stand': 350,
 'kneels': 351,
 'skyscraper': 352,
 'very': 353,
 'tall': 354,
 'distance': 355,
 'camera': 356,
 'bites': 357,
 'hard': 358,
 'treat': 359,
 'biting': 360,
 'baked': 361,
 'good': 362,
 'putting': 363,
 'both': 364,
 'eats': 365,
 'food': 366,
 'table': 367,
 'eating': 368,
 'pizza': 369,
 'tin': 370,
 'dish': 371,
 'mountainside': 372,
 'check': 373,
 'out': 374,
 'view': 375,
 'hilltop': 376,
 'overlooking': 377,
 'valley': 378,
 'hang': 379,
 'top': 380,
 'overlook': 381,
 'rest': 382,
 'ledge': 383,
 'above': 384,
 'moutains': 385,
 'down': 386,
 'many': 387,
 'inflatable': 388,
 'boats': 389,
 'kayakers': 390,
 'railing': 391,
 'rafts': 392,
 'below': 393,
 'crowd': 394,
 'jersey': 395,
 'pose': 396,
 'some': 397,
 'multiracial': 398,
 'posing': 399,
 'picture': 400,
 'asian': 401,
 'blond': 402,
 'background': 403,
 'guy': 404,
 'striped': 405,
 'takeout': 406,
 'television': 407,
 'floor': 408,
 'fast': 409,
 'meal': 410,
 'someone': 411,
 'tv': 412,
 'teens': 413,
 'rail': 414,
 'crowded': 415,
 'takes': 416,
 'jump': 417,
 'skateboard': 418,
 'performing': 419,
 'trick': 420,
 'leans': 421,
 'skateboarder': 422,
 'doing': 423,
 'board': 424,
 'platform': 425,
 'skateboarders': 426,
 'paddling': 427,
 'river': 428,
 'seen': 429,
 'kayaking': 430,
 'paddles': 431,
 'boat': 432,
 'paddle': 433,
 'shallow': 434,
 'girls': 435,
 'ocean': 436,
 'four': 437,
 'children': 438,
 'pajamas': 439,
 'have': 440,
 'pillow': 441,
 'fight': 442,
 'kids': 443,
 'bed': 444,
 'having': 445,
 'constructions': 446,
 'workers': 447,
 'beam': 448,
 'taking': 449,
 'break': 450,
 'construction': 451,
 'i': 452,
 'take': 453,
 'seat': 454,
 'steel': 455,
 'boys': 456,
 'puddle': 457,
 'balloon': 458,
 'mud': 459,
 'sunny': 460,
 'day': 461,
 'appears': 462,
 'wait': 463,
 'hailing': 464,
 'taxi': 465,
 'signaling': 466,
 'traffic': 467,
 'blonde': 468,
 'hair': 469,
 'tube': 470,
 'waving': 471,
 'arm': 472,
 'oncoming': 473,
 'brochure': 474,
 'train': 475,
 'rides': 476,
 'magizine': 477,
 'book': 478,
 'pamphlet': 479,
 'rocky': 480,
 'run': 481,
 'across': 482,
 'stones': 483,
 'area': 484,
 'descends': 485,
 'end': 486,
 'high': 487,
 'diving': 488,
 'pool': 489,
 'dive': 490,
 'window': 491,
 'overshirt': 492,
 'tank': 493,
 'chrome': 494,
 'door': 495,
 'puts': 496,
 'elevator': 497,
 'light': 498,
 'swim': 499,
 'shorts': 500,
 'trunks': 501,
 'arms': 502,
 'outstretched': 503,
 'hiker': 504,
 'bluff': 505,
 'mountains': 506,
 'ski': 507,
 's': 508,
 'landscape': 509,
 'mountain': 510,
 'beautiful': 511,
 'pauses': 512,
 'mountaintop': 513,
 'attempting': 514,
 'purple': 515,
 'low': 516,
 'cut': 517,
 'yard': 518,
 'frisbee': 519,
 'parking': 520,
 'lot': 521,
 'middle': 522,
 'during': 523,
 'heavy': 524,
 'mat': 525,
 'between': 526,
 'suv': 527,
 'pickup': 528,
 'open': 529,
 'busy': 530,
 'terrain': 531,
 'woolly': 532,
 'doberman': 533,
 'chasing': 534,
 'catches': 535,
 'tennis': 536,
 'multicolor': 537,
 'balloons': 538,
 'night': 539,
 'hot': 540,
 'lit': 541,
 'lined': 542,
 'nighttime': 543,
 'helmet': 544,
 'bike': 545,
 'miniature': 546,
 'dirt': 547,
 'bicycle': 548,
 'race': 549,
 'pedals': 550,
 'quickly': 551,
 'bmx': 552,
 'eight': 553,
 'gathered': 554,
 'dark': 555,
 'porch': 556,
 'darkened': 557,
 'room': 558,
 'throwing': 559,
 'cleans': 560,
 'bubbles': 561,
 'suds': 562,
 'wiped': 563,
 'clean': 564,
 'foam': 565,
 'ramp': 566,
 'soapy': 567,
 'getting': 568,
 'cleaned': 569,
 'slides': 570,
 'slide': 571,
 'wading': 572,
 'toys': 573,
 'floating': 574,
 'backyard': 575,
 'sliding': 576,
 'colorful': 577,
 'tubes': 578,
 'falling': 579,
 'wetsuit': 580,
 'toddler': 581,
 'waiting': 582,
 'come': 583,
 'so': 584,
 'droplets': 585,
 'fly': 586,
 'throws': 587,
 'sticks': 588,
 'tongue': 589,
 'make': 590,
 'faces': 591,
 'sticking': 592,
 'look': 593,
 'silly': 594,
 'horse': 595,
 'sweatshirt': 596,
 'fire': 597,
 'barrel': 598,
 'lead': 599,
 'horses': 600,
 'contained': 601,
 'bulldog': 602,
 'sheep': 603,
 'boxer': 604,
 'pushing': 605,
 'anouther': 606,
 'skinny': 607,
 'smaller': 608,
 'int': 609,
 'various': 610,
 'sizes': 611,
 'lady': 612,
 'no': 613,
 'dock': 614,
 'deck': 615,
 'closeup': 616,
 'that': 617,
 'paws': 618,
 'lying': 619,
 'resting': 620,
 'tiled': 621,
 'eyes': 622,
 'rests': 623,
 'patio': 624,
 'bricks': 625,
 'artificial': 626,
 'safety': 627,
 'harness': 628,
 'indoor': 629,
 'rocks': 630,
 'ring': 631,
 'jumphouse': 632,
 'teenage': 633,
 'seating': 634,
 'inflated': 635,
 'family': 636,
 'tractor': 637,
 'polaris': 638,
 'vehicle': 639,
 'played': 640,
 'wheeler': 641,
 'riding': 642,
 'atv': 643,
 'costume': 644,
 'left': 645,
 'sequined': 646,
 'feather': 647,
 'sidewalk': 648,
 'salmon': 649,
 'bikini': 650,
 'outfit': 651,
 'drinking': 652,
 'pop': 653,
 'approached': 654,
 'flamboyant': 655,
 'dressed': 656,
 'feathered': 657,
 'headress': 658,
 'skiiers': 659,
 'forest': 660,
 'skiing': 661,
 'wooded': 662,
 'cross': 663,
 'country': 664,
 'skiers': 665,
 'woodland': 666,
 'trail': 667,
 'woods': 668,
 'hikers': 669,
 'pathway': 670,
 'path': 671,
 'happily': 672,
 'energetic': 673,
 'mother': 674,
 'boardwalk': 675,
 'sea': 676,
 'pier': 677,
 'evening': 678,
 'pony': 679,
 'wintertime': 680,
 'atop': 681,
 'draft': 682,
 'n': 683,
 'daft': 684,
 'pull': 685,
 'cart': 686,
 'golden': 687,
 'sleigh': 688,
 'driven': 689,
 'coat': 690,
 'pulling': 691,
 'carriage': 692,
 'sled': 693,
 'steered': 694,
 'sheer': 695,
 'using': 696,
 'flat': 697,
 'rappels': 698,
 'steep': 699,
 'incline': 700,
 'vest': 701,
 'inside': 702,
 'dome': 703,
 'shaft': 704,
 'cave': 705,
 'shows': 706,
 'spelunkers': 707,
 'cavern': 708,
 'bathed': 709,
 'sunlight': 710,
 'backpackers': 711,
 'lay': 712,
 'dry': 713,
 'camp': 714,
 'gear': 715,
 'chalk': 716,
 'portrait': 717,
 'stream': 718,
 'drawing': 719,
 'barn': 720,
 'like': 721,
 'elaborate': 722,
 'illustration': 723,
 'deep': 724,
 'pile': 725,
 'fountain': 726,
 'fountains': 727,
 'sprayed': 728,
 'corgi': 729,
 'tunnel': 730,
 'course': 731,
 'obstacle': 732,
 'obedience': 733,
 'swimsuit': 734,
 'handrail': 735,
 'bathing': 736,
 'suit': 737,
 'spray': 738,
 'soaked': 739,
 'jet': 740,
 'shower': 741,
 'gets': 742,
 'underwater': 743,
 'headed': 744,
 'swims': 745,
 'gun': 746,
 'foot': 747,
 'aims': 748,
 'fireplace': 749,
 'new': 750,
 'pointed': 751,
 'alone': 752,
 'jagged': 753,
 'snowmobile': 754,
 'mid': 755,
 'snowmobiler': 756,
 'flies': 757,
 'rider': 758,
 'or': 759,
 'machine': 760,
 'pine': 761,
 'rural': 762,
 'snowmobiles': 763,
 'helmets': 764,
 'goggles': 765,
 'snowmobiling': 766,
 'helmeted': 767,
 'drive': 768,
 'atvs': 769,
 'heads': 770,
 'wheel': 771,
 'wheelers': 772,
 'empty': 773,
 'all': 774,
 'gin': 775,
 'airborne': 776,
 'quad': 777,
 'harvested': 778,
 'cornfield': 779,
 'happy': 780,
 'od': 781,
 'playfully': 782,
 'soccer': 783,
 'tucked': 784,
 't': 785,
 'artist': 786,
 'paints': 787,
 'clouds': 788,
 'braids': 789,
 'colors': 790,
 'paper': 791,
 'cyclist': 792,
 'curved': 793,
 'aerodynamic': 794,
 'sharp': 795,
 'curve': 796,
 'pedaling': 797,
 'cows': 798,
 'graze': 799,
 'biker': 800,
 'fetch': 801,
 'pounces': 802,
 'cine': 803,
 'old': 804,
 'fashioned': 805,
 'video': 806,
 'steadies': 807,
 'aim': 808,
 'rosy': 809,
 'cheeks': 810,
 'lips': 811,
 'border': 812,
 'collie': 813,
 'audience': 814,
 'dug': 815,
 'watch': 816,
 'agile': 817,
 'onlookers': 818,
 'closely': 819,
 'smooth': 820,
 'stacking': 821,
 'against': 822,
 'backdrop': 823,
 'shoes': 824,
 'rappeling': 825,
 'headlamp': 826,
 'attached': 827,
 'snakeskin': 828,
 'sprays': 829,
 'frog': 830,
 'public': 831,
 'wood': 832,
 'barrior': 833,
 'animal': 834,
 'bird': 835,
 'seeds': 836,
 'sunflower': 837,
 'clinging': 838,
 'finger': 839,
 'wades': 840,
 'guided': 841,
 'laughs': 842,
 'playful': 843,
 'beige': 844,
 'torwards': 845,
 'outdoor': 846,
 'handstand': 847,
 'does': 848,
 'sheets': 849,
 'upside': 850,
 'snowboard': 851,
 'surfboard': 852,
 'bikes': 853,
 'traveling': 854,
 'worn': 855,
 'motorcycles': 856,
 'motorbikes': 857,
 'follow': 858,
 'garment': 859,
 'flag': 860,
 'crescent': 861,
 'moon': 862,
 'star': 863,
 'gown': 864,
 'muslim': 865,
 'helps': 866,
 'wave': 867,
 'half': 868,
 'naked': 869,
 'chair': 870,
 'older': 871,
 'back': 872,
 'relaxes': 873,
 'adobe': 874,
 'where': 875,
 'bicycles': 876,
 'propped': 877,
 'cap': 878,
 'close': 879,
 'parked': 880,
 'relaxing': 881,
 'folding': 882,
 'topless': 883,
 'slippers': 884,
 'navy': 885,
 'reclining': 886,
 'hauling': 887,
 'retrieve': 888,
 'mouths': 889,
 'tug': 890,
 'chew': 891,
 'haired': 892,
 'bottled': 893,
 'drink': 894,
 'tilted': 895,
 'spiked': 896,
 'party': 897,
 'streets': 898,
 'they': 899,
 'women': 900,
 'parade': 901,
 'neck': 902,
 'vegetation': 903,
 'filled': 904,
 'bushes': 905,
 'creating': 906,
 'splash': 907,
 'seaweed': 908,
 'lav': 909,
 'swimmers': 910,
 'kelp': 911,
 'foreground': 912,
 'sandals': 913,
 'short': 914,
 'sleeved': 915,
 'pinstripe': 916,
 'snows': 917,
 'furry': 918,
 'attempts': 919,
 'itself': 920,
 'self': 921,
 'backpacks': 922,
 'placed': 923,
 'cardboard': 924,
 'bus': 925,
 'station': 926,
 'bouncing': 927,
 'folded': 928,
 'beds': 929,
 'bedroom': 930,
 'snowboarder': 931,
 'slope': 932,
 'boarders': 933,
 'snowboarders': 934,
 'slopes': 935,
 'clothing': 936,
 'store': 937,
 'opening': 938,
 'stores': 939,
 'piece': 940,
 'attire': 941,
 'car': 942,
 'strip': 943,
 'boots': 944,
 'stepping': 945,
 'van': 946,
 'wear': 947,
 'game': 948,
 'plants': 949,
 'crossing': 950,
 'greenery': 951,
 'suspension': 952,
 'tropical': 953,
 'caution': 954,
 'sign': 955,
 'beside': 956,
 'bright': 957,
 'truck': 958,
 'others': 959,
 'helping': 960,
 'step': 961,
 'pulled': 962,
 'passengers': 963,
 'load': 964,
 'brightly': 965,
 'poses': 966,
 'pig': 967,
 'hugs': 968,
 'who': 969,
 'embracing': 970,
 'event': 971,
 'hugging': 972,
 'hooded': 973,
 'stretch': 974,
 'bicyclist': 975,
 'spandex': 976,
 'biking': 977,
 'jogging': 978,
 'headset': 979,
 'walkman': 980,
 'jogs': 981,
 'headphones': 982,
 'plant': 983,
 'corner': 984,
 'bicyclists': 985,
 'intersection': 986,
 'bikers': 987,
 'stop': 988,
 'town': 989,
 'without': 990,
 'guiding': 991,
 'wagon': 992,
 'escorts': 993,
 'leading': 994,
 'drawn': 995,
 'shetland': 996,
 'hits': 997,
 'tee': 998,
 'practices': 999,
 ...}

In [22]:
for word in bn_counter:
  if word not in bn_vocab:
    bn_vocab[word]=len(bn_vocab)

In [23]:
bn_vocab

{'<oov>': 0,
 '<sos>': 1,
 '<eos>': 2,
 'একটি': 3,
 'গোলাপী': 4,
 'জামা': 5,
 'পরা': 6,
 'বাচ্চা': 7,
 'মেয়ে': 8,
 'বাড়ির': 9,
 'প্রবেশ': 10,
 'পথের': 11,
 'সিঁড়ি': 12,
 'বেয়ে': 13,
 'উঠছে': 14,
 'শিশু': 15,
 'কাঠের': 16,
 'বাড়িতে': 17,
 'ঢুকছে': 18,
 'তার': 19,
 'খেলাঘরে': 20,
 'ছোট': 21,
 'মেয়েটি': 22,
 'খেলার': 23,
 'ঘরের': 24,
 'সিড়ি': 25,
 'গোলাপি': 26,
 'পড়া': 27,
 'তৈরি': 28,
 'ঘরে': 29,
 'করছে': 30,
 'কালো': 31,
 'কুকুর': 32,
 'এবং': 33,
 'ছোপওয়ালা': 34,
 'ঝগড়া': 35,
 'তিন': 36,
 'রঙা': 37,
 'কুকুরের': 38,
 'সাথে': 39,
 'রাস্তায়': 40,
 'খেলছে': 41,
 'ও': 42,
 'সাদা': 43,
 'বাদামি': 44,
 'ছোপযুক্ত': 45,
 'রাস্তায়': 46,
 'একে': 47,
 'অপরের': 48,
 'দিকে': 49,
 'তাকিয়ে': 50,
 'আছে': 51,
 'ভিন্ন': 52,
 'জাতের': 53,
 'দুটি': 54,
 'রাস্তার': 55,
 'পাশে': 56,
 'দুইটি': 57,
 'পরস্পরের': 58,
 'এগিয়ে': 59,
 'যাচ্ছ': 60,
 'রঙে': 61,
 'মাখা': 62,
 'হাতে': 63,
 'রঙের': 64,
 'বাটিতে': 65,
 'হাত': 66,
 'দিয়ে': 67,
 'রঙ': 68,
 'আঁকা': 69,
 'রংধনুর': 70,
 'সামনে': 71,
 'বসে': 72,
 'ছোটো': 73,
 'মেয়ে': 74,
 'ঘাসে': 75,
 'আঙুলে': 76,
 'রং': 77,
 'নিয়ে': 78,
 'খেলা': 79,
 'রংধনু': 80,
 'ক্যানভসের': 81,
 'চুলে': 82,
 'বেণী': 83,
 'করা': 84,
 'চিত্রের': 85,
 'বেনী': 86,
 'অল্প': 87,
 'বয়সী': 88,
 'বাইরে': 89,
 'ঘাসের': 90,
 'উপর': 91,
 'একজন': 92,
 'পুরুষ': 93,
 'টেবিলের': 94,
 'শুয়ে': 95,
 'যখন': 96,
 'মানুষ': 97,
 'বেঞ্চিতে': 98,
 'শুয়ে': 99,
 'যার': 100,
 'কুকুরও': 101,
 'বাধা': 102,
 'ব্যক্তি': 103,
 'বেঞ্চে': 104,
 'ঘুমাচ্ছে': 105,
 'নগ্নদেহী': 106,
 'লোক': 107,
 'পোষা': 108,
 'কুকুরকে': 109,
 'বাগানে': 110,
 'লম্বা': 111,
 'আসনে': 112,
 'মাটিতে': 113,
 'থাকা': 114,
 'কুকুরটির': 115,
 'শিকল': 116,
 'ধরে': 117,
 'লোকটি': 118,
 'কমলা': 119,
 'টুপি': 120,
 'পরিহিত': 121,
 'কোনোকিছুর': 122,
 'পরেছ': 123,
 'চশমাও': 124,
 'পরেছে': 125,
 'চশমাযুক্ত': 126,
 'ব্লিটজ': 127,
 'পরেছেন': 128,
 'চশমা': 129,
 'বিয়ারের': 130,
 'কৌটা': 131,
 'বানানো': 132,
 'পরে': 133,
 'কান': 134,
 'ফোঁড়ানো': 135,
 'ব্যক্তিটি': 136,
 'দড়ি': 137,
 'নির্মিত': 138,
 'জালের': 139,
 'লাল': 140,
 'দড়ি': 141,
 'দড়ির': 142,
 'সেতু': 143,
 'আরোহণ': 144,
 'মাঠে': 145,
 'রশি': 146,
 'আঁকড়ে': 147,
 'বাচ্চাটি': 148,
 'দড়িতে': 149,
 'চড়ে': 150,
 'বেড়ি': 151,
 'যুক্ত': 152,
 'আবৃত': 153,
 'দৌড়াচ্ছে': 154,
 'সাদাকালো': 155,
 'দৌড়াচ্ছে': 156,
 'বোস্টন': 157,
 'টেরিয়ার': 158,
 'টেরিয়ার': 159,
 'বেড়ার': 160,
 'ঘন': 161,
 'সবুজ': 162,
 'মধ্যে': 163,
 'দৌড়ে': 164,
 'যাচ্ছে': 165,
 'কুকুরটি': 166,
 'তীরের': 167,
 'কাছে': 168,
 'মাথা': 169,
 'ঝাকাচ্ছে': 170,
 'এর': 171,
 'বল': 172,
 'সমুদ্রের': 173,
 'পাড়ে': 174,
 'তীরে': 175,
 'দাঁড়িয়ে': 176,
 'শরীর': 177,
 'থেকে': 178,
 'জল': 179,
 'ঝেড়ে': 180,
 'ফেলছে': 181,
 'জলের': 182,
 'ধারে': 183,
 'খেলায়': 184,
 'রত': 185,
 'কানওয়ালা': 186,
 'একদিকে': 187,
 'বাঁকিয়ে': 188,
 'পানির': 189,
 'দাড়িয়ে': 190,
 'শহরের': 191,
 'পাথর': 192,
 'দেয়ালের': 193,
 'বালক': 194,
 'হাসছে': 195,
 'ছেলে': 196,
 'অ্যদিকে': 197,
 'সবর্পরি': 198,
 'কাজ': 199,
 'পাথরের': 200,
 'দেওয়ালের': 201,
 'রাস্তা': 202,
 'পাথুরে': 203,
 'হেঁটে': 204,
 'পেছনে': 205,
 'ধাতব': 206,
 'খাম্বা': 207,
 'রয়েছ': 208,
 'শার্ট': 209,
 'আর': 210,
 'নীল': 211,
 'জিন্স': 212,
 'পড়া': 213,
 'হাস্যোজ্জ্বল': 214,
 'ছেলেটি': 215,
 'সম্পূর্ণ': 216,
 'উল্টোদিকে': 217,
 'মুখ': 218,
 'করে': 219,
 'লোকটির': 220,
 'প্রাচীরের': 221,
 'দাঁড়িয়ে': 222,
 'গাছের': 223,
 'গুঁড়ির': 224,
 'দিয়ে': 225,
 'লাফ': 226,
 'দিচ্ছে': 227,
 'ধূসর': 228,
 'ভেঙে': 229,
 'বড়': 230,
 'পতিত': 231,
 'লাফিয়ে': 232,
 'গলাবন্ধ': 233,
 'পড়ে': 234,
 'কুঁদা': 235,
 'পার': 236,
 'বরফের': 237,
 'মাঝ': 238,
 'উপরে': 239,
 'মাঝে': 240,
 'বাদামী': 241,
 'বরফে': 242,
 'ঢাকা': 243,
 'মাঠের': 244,
 'শ্বেত': 245,
 'পৃষ্ঠদেশে': 246,
 'বেড়াচ্ছে': 247,
 'আরেকজন': 248,
 'স্কিচালক': 249,
 'কে': 250,
 'কিছু': 251,
 'ছবি': 252,
 'দেখাচ্ছেন': 253,
 'স্কি': 254,
 'অন্যজন': 255,
 'চিত্র': 256,
 'প্রদর্শন': 257,
 'তুষারে': 258,
 'রাখা': 259,
 'ফ্রেমবন্দি': 260,
 'ছবিগুলো': 261,
 'দেখছে': 262,
 'পাশের': 263,
 'ফ্রেমযুক্ত': 264,
 'করতে': 265,
 'বিক্রয়যোগ্য': 266,
 'চিত্রকর্মগুলোর': 267,
 'তাকিয়ে': 268,
 'ব্যক্তির': 269,
 'কোলাজ': 270,
 'খাড়া': 271,
 'পাহাড়': 272,
 'আরোহন': 273,
 'একদল': 274,
 'পাথুর': 275,
 'উঠার': 276,
 'দেওয়ালে': 277,
 'শিলায়': 278,
 'চড়ছে': 279,
 'চড়ার': 280,
 'প্রস্তুতি': 281,
 'নিচ্ছে': 282,
 'সাত': 283,
 'পর্বতারোহী': 284,
 'শিলামুখ': 285,
 'আরেক': 286,
 'কয়েকজন': 287,
 'আরোহী': 288,
 'একসাথে': 289,
 'করছেন': 290,
 'পোশাক': 291,
 'নজর': 292,
 'রেখেছে': 293,
 'রশিটি': 294,
 'ঘাসযুক্ত': 295,
 'জায়গার': 296,
 'পানি': 297,
 'ছিটানো': 298,
 'যন্ত্র': 299,
 'ছিটকে': 300,
 'ধরতে': 301,
 'চেষ্টা': 302,
 'বদামী': 303,
 'জলসেচনের': 304,
 'পাইপের': 305,
 'লনে': 306,
 'দেওয়ার': 307,
 'নলের': 308,
 'হৌজ': 309,
 'স্প্রিংকলার': 310,
 'পালাচ্ছে': 311,
 'কাছাকাছি': 312,
 'গাড়ি': 313,
 'এমন': 314,
 'ছুঁড়ে': 315,
 'দেয়া': 316,
 'বস্তুটি': 317,
 'ধরার': 318,
 'হলুদ': 319,
 'খেলনা': 320,
 'চলেছে': 321,
 'উড়তে': 322,
 'জন্য': 323,
 'প্রস্তুত': 324,
 'বলের': 325,
 'পিছনে': 326,
 'শূণ্যে': 327,
 'লাফাচ্ছে': 328,
 'খেলনার': 329,
 'দিলো': 330,
 'লাফালাফি': 331,
 'শুন্যে': 332,
 'নিয়ে': 333,
 'শহরে': 334,
 'মহিলা': 335,
 'কিনারায়': 336,
 'বড়': 337,
 'হ্রদের': 338,
 'কিনারায়': 339,
 'একা': 340,
 'হাঁস': 341,
 'হ্রদে': 342,
 'সাঁতার': 343,
 'কাটছে': 344,
 'দীঘির': 345,
 'উদ্যান': 346,
 'ঘেরা': 347,
 'পানিতে': 348,
 'হাঁসের': 349,
 'তরুণ': 350,
 'নাড়াচ্ছে': 351,
 'দুইজন': 352,
 'আকাশরেখার': 353,
 'মুখোমুখি': 354,
 'হয়ে': 355,
 'পুকুরের': 356,
 'ঘোরানোর': 357,
 'এক': 358,
 'দম্পতি': 359,
 'বাচ্চাটিক্': 360,
 'ঘসের': 361,
 'তাদের': 362,
 'বাচ্চার': 363,
 'বহনকরার': 364,
 'গাড়ী': 365,
 'নবজাতক': 366,
 'শিশুকে': 367,
 'নিচে': 368,
 'আদর': 369,
 'শিশুর': 370,
 'স্ট্রোলারের': 371,
 'গলার': 372,
 'বাধাবুলি': 373,
 'সাগরের': 374,
 'ছিটাচ্ছে': 375,
 'টি': 376,
 'মধ্য': 377,
 'এটি': 378,
 'যা': 379,
 'গর্ত': 380,
 'খুঁড়ছে': 381,
 'জমে': 382,
 'যাওয়া': 383,
 'পুকুরে': 384,
 'ছিদ্র': 385,
 'খুঁড়ছে': 386,
 'জমাট': 387,
 'বাঁধা': 388,
 'আছেন': 389,
 'দুই': 390,
 'জন': 391,
 'মাছ': 392,
 'ধরছে': 393,
 'সমুদ্রতীরে': 394,
 'নরম': 395,
 'বালির': 396,
 'সমুদ্র': 397,
 'সৈকতে': 398,
 'ঘুরছে': 399,
 'সৈকতের': 400,
 'বালুতে': 401,
 'বালুকাময়': 402,
 'তাম্রবর্ণের': 403,
 'একজল': 404,
 'বরফ': 405,
 'বেয়ে': 406,
 'উঠতে': 407,
 'আইস': 408,
 'পিকস': 409,
 'ক্র্যাম্পন': 410,
 'জুতো': 411,
 'ব্যবহার': 412,
 'পাহাড়': 413,
 'বরফারোহী': 414,
 'ঝর্না': 415,
 'গাঁইতি': 416,
 'দেয়ালে': 417,
 'মুখে': 418,
 'জিনিস': 419,
 'রয়েছে': 420,
 'বস্তু': 421,
 'ভেজা': 422,
 'বহন': 423,
 'ক্যানভাসে': 424,
 'মোড়ানো': 425,
 'ছইওয়ালা': 426,
 'সরু': 427,
 'নৌকায়': 428,
 'ভেসে': 429,
 'বেড়াচ্ছে': 430,
 'বহিরাবরণ': 431,
 'ডোঙ্গা': 432,
 'শান্ত': 433,
 'কায়াকিং': 434,
 'নৌকা': 435,
 'বাইছে': 436,
 'ক্যানভাস': 437,
 'মোড়া': 438,
 'ছইওয়ালা': 439,
 'জলাশয়ে': 440,
 'ঘুরে': 441,
 'লাফঝাঁপ': 442,
 'চত্বরে': 443,
 'সম্মুখ': 444,
 'ঝাঁপ': 445,
 'সময়': 446,
 'ফেলে': 447,
 'চকোলেট': 448,
 'ল্যাব': 449,
 'আগেই': 450,
 'ব্ল্যাক': 451,
 'ফেলেছে': 452,
 'লাঠি': 453,
 'গোল': 454,
 'হাঁটু': 455,
 'গেঁড়ে': 456,
 'গোলরক্ষক': 457,
 'হিসেবে': 458,
 'হকি': 459,
 'রিংক': 460,
 'এ': 461,
 'হয়ে': 462,
 'ডান': 463,
 'স্টিক': 464,
 'গোলের': 465,
 'গেড়ে': 466,
 'জ্যাকেট': 467,
 'নত': 468,
 'কাচের': 469,
 'দালানের': 470,
 'আধুনিক': 471,
 'শিল্প': 472,
 'স্থাপত্যের': 473,
 'কার্যালয়ের': 474,
 'ভাস্কর্যেরসামনে': 475,
 'খবরের': 476,
 'কাগজ': 477,
 'পড়ছে': 478,
 'বিশাল': 479,
 'ভাস্কর্যের': 480,
 'অভিমুখে': 481,
 'আছ': 482,
 'ভাষ্কর্য': 483,
 'চত্বরের': 484,
 'থলে': 485,
 'কাঁধে': 486,
 'তাবু': 487,
 'স্থাপন': 488,
 'হচ্ছে': 489,
 'দুজন': 490,
 'শিকার': 491,
 'করার': 492,
 'তাঁবুতে': 493,
 'হিমায়িত': 494,
 'লেকের': 495,
 'ওপর': 496,
 'কুঁড়েঘর': 497,
 'বসাচ্ছে': 498,
 'ত্রিপলের': 499,
 'পৃষ্ঠতলে': 500,
 'তাঁবু': 501,
 'কাঠামোর': 502,
 'দু': 503,
 'তিনটি': 504,
 'কুকুরগুলো': 505,
 'খোলা': 506,
 'আকাশের': 507,
 'ওদের': 508,
 'পাহাড়ের': 509,
 'অবাক': 510,
 'দৃষ্টিতে': 511,
 'ব্যাক্তি': 512,
 'গেড়ে': 513,
 'গগনচুম্বী': 514,
 'ভবনের': 515,
 'অনেক': 516,
 'উঁচু': 517,
 'রয়েছে': 518,
 'আকাশচুম্বি': 519,
 'অট্টালিকা': 520,
 'অতি': 521,
 'উচ্চ': 522,
 'অট্টালিকাটির': 523,
 'তুলতে': 524,
 'চিত্রগাহকের': 525,
 'পিৎজা': 526,
 'খাচ্ছে': 527,
 'শেঁকা': 528,
 'খাবারে': 529,
 'কামড়': 530,
 'একটা': 531,
 'খাবার': 532,
 'টেবিলে': 533,
 'খায়': 534,
 'বালকটি': 535,
 'টিনের': 536,
 'ডিসে': 537,
 'পিজ্জা': 538,
 'কয়েকজন': 539,
 'প্রকৃতিররূপ': 540,
 'পাহাড়চূড়া': 541,
 'তিনজন': 542,
 'উপত্যকা': 543,
 'দর্শন': 544,
 'আড্ডা': 545,
 'উপেক্ষা': 546,
 'পাহাড়ের': 547,
 'বিশ্রাম': 548,
 'ভাসমান': 549,
 'নৌকাসমূহের': 550,
 'কায়াকারদেরকে': 551,
 'অনেকগুলো': 552,
 'ভেলা': 553,
 'নৌকার': 554,
 'জনতাকে': 555,
 'জার্সি': 556,
 'কৌতুহল': 557,
 'নৌকাগুলোর': 558,
 'নারী': 559,
 'তুলছে': 560,
 'অবস্থায়': 561,
 'পেছন': 562,
 'মহিলার': 563,
 'মুখের': 564,
 'সেদিকে': 565,
 'বহু': 566,
 'সংস্কৃত': 567,
 'ছবির': 568,
 'পোজ': 569,
 'দিচ্ছেন': 570,
 'এশিয়ান': 571,
 'স্বর্ণকেশী': 572,
 'পিছনের': 573,
 'তাদেরকে': 574,
 'ডোরাকাটা': 575,
 'জ্যাকেটের': 576,
 'কামরাচ্ছে': 577,
 'টেলিভিশন': 578,
 'কিনে': 579,
 'বাসায়': 580,
 'আনা': 581,
 'মেঝেতে': 582,
 'টিভির': 583,
 'মেয়ের': 584,
 'ভাসছে': 585,
 'টেলিভিশনের': 586,
 'ফাস্ট': 587,
 'ফুড': 588,
 'যুবক': 589,
 'কেউ': 590,
 'হেলান': 591,
 'শৈলশিরার': 592,
 'সমুদ্রসৈকত': 593,
 'পর্যবেক্ষণ': 594,
 'দেয়ালে': 595,
 'কিশোরীরা': 596,
 'বসেছিল': 597,
 'লোকের': 598,
 'ভিড়': 599,
 'তরুণী': 600,
 'জনবহুল': 601,
 'পাটাতনের': 602,
 'স্কেটবোর্ডের': 603,
 'সাহায্যে': 604,
 'সময়': 605,
 'স্কেটবোর্ড': 606,
 'তাকে': 607,
 'কারিকুরি': 608,
 'দেখাচ্ছে': 609,
 'আরেকটি': 610,
 'ঝুঁকে': 611,
 'স্কেটবোর্ডার': 612,
 'চাতুরী': 613,
 'তখন': 614,
 'অন্য': 615,
 'তা': 616,
 'সমতল': 617,
 'স্থানে': 618,
 'খেলোয়াড়': 619,
 'দেখা': 620,
 'বালিকা': 621,
 'দাঁড়ের': 622,
 'নদী': 623,
 'পাড়ি': 624,
 'নদীতে': 625,
 'চালাচ্ছেন': 626,
 'বৈঠা': 627,
 'বৈঠাসহ': 628,
 'কবরী': 629,
 'অগভীর': 630,
 'সমুদ্রপারে': 631,
 'সমুদ্রে': 632,
 'চুল': 633,
 'চার': 634,
 'দল': 635,
 'ঘুমের': 636,
 'পরিধান': 637,
 'বালিশ': 638,
 'যুদ্ধ': 639,
 'বাচ্চাদের': 640,
 'বিছানার': 641,
 'শিশুদের': 642,
 'বাচ্চারা': 643,
 'বালিশের': 644,
 'লড়াই': 645,
 'মিলে': 646,
 'নির্মাণাধীন': 647,
 'কর্মী': 648,
 'কড়িকাঠে': 649,
 'জিরিয়ে': 650,
 'নির্মাণশ্রমিক': 651,
 'নির্মাণ': 652,
 'কড়িকাঠের': 653,
 'শ্রমিক': 654,
 'ইস্পাতের': 655,
 'দন্ডের': 656,
 'বিরতি': 657,
 'নেন': 658,
 'শিশুরা': 659,
 'কর্দমাক্ত': 660,
 'ক্ষুদ্র': 661,
 'ডোবায়': 662,
 'রৌদ্রময়': 663,
 'দিনে': 664,
 'বেলুন': 665,
 'কাদার': 666,
 'খেলে': 667,
 'জলে': 668,
 'সোনালী': 669,
 'চুলের': 670,
 'বাহনের': 671,
 'অপেক্ষা': 672,
 'ট্যাক্সি': 673,
 'থামানোর': 674,
 'ট্র্যাফিক': 675,
 'সিগন্যাল': 676,
 'টপ': 677,
 'নাড়ছেন': 678,
 'পোশাকের': 679,
 'অগ্রসরমান': 680,
 'যানবাহনের': 681,
 'প্রতি': 682,
 'হাতটি': 683,
 'রেখেছেন': 684,
 'ট্রেনে': 685,
 'চড়া': 686,
 'সম্বন্ধীয়': 687,
 'প্রচারপত্র': 688,
 'অল্পবয়সী': 689,
 'ম্যাগাজিন': 690,
 'ভ্রমণরত': 691,
 'ট্রেন': 692,
 'ভ্রমণ': 693,
 'সম্পর্কিত': 694,
 'বই': 695,
 'পড়ছে': 696,
 'সিটে': 697,
 'রেল': 698,
 'পুস্তক': 699,
 'শিশুটি': 700,
 'ভ্রমণের': 701,
 'পাথরে': 702,
 'ধাওয়া': 703,
 'জলাধারের': 704,
 'পশ্চাদপটে': 705,
 'অঞ্চলে': 706,
 'ছুটে': 707,
 'যায়': 708,
 'দেয়ার': 709,
 'জন্যে': 710,
 'ব্যবহৃত': 711,
 'পাটাতন': 712,
 'ডাইভিং': 713,
 'বোর্ড': 714,
 'লাফিয়ে': 715,
 'নিচের': 716,
 'সাঁতারের': 717,
 'পড়লো': 718,
 'স্থান': 719,
 'ঝাঁপিয়ে': 720,
 'পুলের': 721,
 'জানালার': 722,
 'গায়ের': 723,
 'খুলছে': 724,
 'হাতা': 725,
 'কাটা': 726,
 'হলদে': 727,
 'দরজার': 728,
 'লিফটের': 729,
 'নিজের': 730,
 'জামাটি': 731,
 'পরছে': 732,
 'নিচু': 733,
 'উত্তোলক': 734,
 'যন্ত্রের': 735,
 'হালকা': 736,
 'পশমি': 737,
 'তামাটে': 738,
 'বালুময়': 739,
 'চলছে': 740,
 'বিচের': 741,
 'কাটার': 742,
 'পোশাকে': 743,
 'আলোকচিত্রী': 744,
 'কাপড়': 745,
 'পদব্রজে': 746,
 'ভ্রমণকারী': 747,
 'পর্বত': 748,
 'সমূহকে': 749,
 'বরফাবৃত': 750,
 'নিম্নভূমি': 751,
 'তুষার': 752,
 'পর্বতকে': 753,
 'তত্ত্বাবধান': 754,
 'প্রাকৃতিক': 755,
 'দৃশ্য': 756,
 'উপভোগ': 757,
 'স্কাইয়ার': 758,
 'পাহাড়চূড়ায়': 759,
 'থামলেন': 760,
 'কম': 761,
 'ছাটা': 762,
 'উঠানে': 763,
 'বেগুনী': 764,
 'বস্তুকে': 765,
 'খেলনাটি': 766,
 'ফ্রিসবি': 767,
 'পেতে': 768,
 'দেয়': 769,
 'বেগুনি': 770,
 'খেলনাটা': 771,
 'উঠেছে': 772,
 'প্যান্ট': 773,
 'রাখার': 774,
 'ভারী': 775,
 'যানজটের': 776,
 'মাঝখানে': 777,
 'এসইউভি': 778,
 'দরজা': 779,
 'সহ': 780,
 'পিকআপের': 781,
 'মধ্যকার': 782,
 'পার্কিং': 783,
 'মাদুরের': 784,
 'অর্ধনগ্ন': 785,
 'ব্যস্ত': 786,
 'সড়কের': 787,
 'বালিযুক্ত': 788,
 'বিস্তৃত': 789,
 'ভূমিখণ্ডে': 790,
 'ডোবারম্যান': 791,
 'কুকুরটিকে': 792,
 'তাড়া': 793,
 'আকারের': 794,
 'বালুর': 795,
 'অপরকে': 796,
 'ফেললো': 797,
 'টেনিস': 798,
 'বাতাসে': 799,
 'ছুড়ে': 800,
 'দেওয়া': 801,
 'করছিল': 802,
 'রাতের': 803,
 'বেলায়': 804,
 'ফানুস': 805,
 'আকাশে': 806,
 'জ্বলন্ত': 807,
 'লোকেরা': 808,
 'পার্কে': 809,
 'গরম': 810,
 'হাওয়া': 811,
 'ভর্তি': 812,
 'বেলুনগুলি': 813,
 'আকাশযান': 814,
 'রাতে': 815,
 'জনতার': 816,
 'সাতটি': 817,
 'সারিবদ্ধভাবে': 818,
 'হেলমেট': 819,
 'সাইকেল': 820,
 'চালাচ্ছে': 821,
 'ময়লা': 822,
 'চালিয়ে': 823,
 'পাহাড়ি': 824,
 'দিলে': 825,
 'প্রতিযোগিতায়': 826,
 'বাইসাইকেল': 827,
 'ক্ষুদে': 828,
 'প্রতিযোগী': 829,
 'সাইকেলে': 830,
 'দ্রুত': 831,
 'প্যাডেল': 832,
 'আটজন': 833,
 'চতুর্দিকে': 834,
 'জড়ো': 835,
 'হয়েছে': 836,
 'অন্ধকারে': 837,
 'জমায়েত': 838,
 'বারান্দায়': 839,
 'চারপাশে': 840,
 'অন্ধকার': 841,
 'ছোঁড়ার': 842,
 'বিচে': 843,
 'সাবানের': 844,
 'ফেনা': 845,
 'সাফ': 846,
 'মুছিয়ে': 847,
 'নিলো': 848,
 'বুদবুদে': 849,
 'ডেকে': 850,
 'গেছে': 851,
 'ফেনায়': 852,
 'বাজে': 853,
 'ঢালু': 854,
 'পথে': 855,
 'সাবান': 856,
 'পরিষ্কার': 857,
 'সাহায্য': 858,
 'পিছল': 859,
 'পিছলে': 860,
 'খেলনায়': 861,
 'সমৃদ্ধ': 862,
 'কৃত্রিম': 863,
 'বাড়ির': 864,
 'উঠোনে': 865,
 'স্লাইডে': 866,
 'রঙিন': 867,
 'টিউবের': 868,
 'পথ': 869,
 'গড়িয়ে': 870,
 'বেলুনগুলির': 871,
 'স্লাইড': 872,
 'ডুবুরিদের': 873,
 'ডুবুরি': 874,
 'ফেলা': 875,
 'আবার': 876,
 'বাচ্চাকে': 877,
 'শূন্যে': 878,
 'ছুড়ছে': 879,
 'নীচে': 880,
 'নামার': 881,
 'যাতে': 882,
 'সে': 883,
 'পারে': 884,
 'ছোট্ট': 885,
 'ছেলেকে': 886,
 'হাওয়ায়': 887,
 'ছুড়ে': 888,
 'ফোঁটা': 889,
 'উড়ে': 890,
 'যাওয়ার': 891,
 'বাতাসের': 892,
 'ক্যামেরায়': 893,
 'তোলার': 894,
 'জিহ্বা': 895,
 'তোলা': 896,
 'মুখাভংগি': 897,
 'বয়স্ক': 898,
 'ক্যামেরার': 899,
 'অন্যটি': 900,
 'জিহ্বাটি': 901,
 'বের': 902,
 'করেছে': 903,
 'হাস্যজ্জল': 904,
 'এদের': 905,
 'নির্বোধ': 906,
 'আকৃতির': 907,
 'বানাচ্ছে': 908,
 'সেনালী': 909,
 'ঘোড়া': 910,
 'সোয়েটার': 911,
 'পিপেতে': 912,
 'আগুনের': 913,
 'মেয়েটি': 914,
 'ঘোড়ার': 915,
 'লাগাম': 916,
 'ঘোড়া': 917,
 'শিখার': 918,
 'অবস্থান': 919,
 'আগুন': 920,
 'বুলডগ': 921,
 'শিপডগ': 922,
 'বক্সার': 923,
 'ধাক্কা': 924,
 'শুকনো': 925,
 'ময়লার': 926,
 'দাড়িয়ে': 927,
 'অবস্থিত': 928,
 'খালি': 929,
 'পাটাতনে': 930,
 'ফেরিঘাটে': 931,
 'জাহাজের': 932,
 'গায়ের': 933,
 'ডকে': 934,
 'কাছ': 935,
 'ধারণকৃত': 936,
 'থাবার': 937,
 'রেখে': 938,
 'লাগিয়ে': 939,
 'চোখ': 940,
 'টালি': 941,
 'ছাত্তয়া': 942,
 'নুইয়ে': 943,
 'বহিঃপ্রাঙ্গনের': 944,
 'ইটের': 945,
 'নিরাপত্তা': 946,
 'সজ্জিত': 947,
 'দেয়াল': 948,
 'অর্ন্তবর্তী': 949,
 'মহিলাটি': 950,
 'মেয়েটা': 951,
 'সুরক্ষা': 952,
 'সামগ্রী': 953,
 'পাহাড়ে': 954,
 'দেয়াল': 955,
 'ভাসনযোগ্য': 956,
 'রিং': 957,
 'কিশোর': 958,
 'ফাঁপা': 959,
 'স্ফীত': 960,
 '২': 961,
 'ফোলানো': 962,
 'সুন্দর': 963,
 'পরিবার': 964,
 'হালচাষের': 965,
 'চড়ে': 966,
 'বেশ': 967,
 'কয়েকটি': 968,
 'পোলারিস': 969,
 'গাড়িতে': 970,
 'চাকার': 971,
 'গাড়িতে': 972,
 'চারটি': 973,
 'বামদিকে': 974,
 'পরিচ্ছদ': 975,
 'দাঁড়ানো': 976,
 'জড়ির': 977,
 'পাখাযুক্ত': 978,
 'কাপড়ে': 979,
 'ফিকে': 980,
 'অন্তর্বাস': 981,
 'তরুণীর': 982,
 'কোমল': 983,
 'পানীয়': 984,
 'পান': 985,
 'মানুষের': 986,
 'বিকিনি': 987,
 'পাগড়ি': 988,
 'সুসজ্জিত': 989,
 'এসেছেন': 990,
 'স্কিচালকেরা': 991,
 'বনের': 992,
 'পাহাড়ে': 993,
 'মাঝের': 994,
 'জায়গায়': 995,
 'স্কিইং': 996,
 'জঙ্গলের': 997,
 'অরণ্যে': 998,
 'অনুসরণ': 999,
 ...}

In [24]:
en_vocab

{'<oov>': 0,
 'a': 1,
 'child': 2,
 'in': 3,
 'pink': 4,
 'dress': 5,
 'is': 6,
 'climbing': 7,
 'up': 8,
 'set': 9,
 'of': 10,
 'stairs': 11,
 'an': 12,
 'entry': 13,
 'way': 14,
 'girl': 15,
 'going': 16,
 'into': 17,
 'wooden': 18,
 'building': 19,
 'little': 20,
 'playhouse': 21,
 'the': 22,
 'to': 23,
 'her': 24,
 'cabin': 25,
 'black': 26,
 'dog': 27,
 'and': 28,
 'spotted': 29,
 'are': 30,
 'fighting': 31,
 'tri': 32,
 'colored': 33,
 'playing': 34,
 'with': 35,
 'each': 36,
 'other': 37,
 'on': 38,
 'road': 39,
 'white': 40,
 'brown': 41,
 'spots': 42,
 'staring': 43,
 'at': 44,
 'street': 45,
 'two': 46,
 'dogs': 47,
 'different': 48,
 'breeds': 49,
 'looking': 50,
 'pavement': 51,
 'moving': 52,
 'toward': 53,
 'covered': 54,
 'paint': 55,
 'sits': 56,
 'front': 57,
 'painted': 58,
 'rainbow': 59,
 'hands': 60,
 'bowl': 61,
 'sitting': 62,
 'large': 63,
 'small': 64,
 'grass': 65,
 'plays': 66,
 'fingerpaints': 67,
 'canvas': 68,
 'it': 69,
 'there': 70,
 'pigtails': 71,
 'painting': 72,
 'young': 73,
 'outside': 74,
 'man': 75,
 'lays': 76,
 'bench': 77,
 'while': 78,
 'his': 79,
 'by': 80,
 'him': 81,
 'which': 82,
 'also': 83,
 'tied': 84,
 'sleeping': 85,
 'next': 86,
 'shirtless': 87,
 'lies': 88,
 'park': 89,
 'laying': 90,
 'holding': 91,
 'leash': 92,
 'ground': 93,
 'orange': 94,
 'hat': 95,
 'starring': 96,
 'something': 97,
 'wears': 98,
 'glasses': 99,
 'gauges': 100,
 'wearing': 101,
 'blitz': 102,
 'beer': 103,
 'can': 104,
 'crocheted': 105,
 'pierced': 106,
 'ears': 107,
 'rope': 108,
 'net': 109,
 'red': 110,
 'roping': 111,
 'climbs': 112,
 'bridge': 113,
 'grips': 114,
 'onto': 115,
 'ropes': 116,
 'playground': 117,
 'running': 118,
 'grassy': 119,
 'garden': 120,
 'surrounded': 121,
 'fence': 122,
 'through': 123,
 'boston': 124,
 'terrier': 125,
 'lush': 126,
 'green': 127,
 'runs': 128,
 'near': 129,
 'shakes': 130,
 'its': 131,
 'head': 132,
 'shore': 133,
 'ball': 134,
 'edge': 135,
 'beach': 136,
 'feet': 137,
 'stands': 138,
 'shaking': 139,
 'off': 140,
 'water': 141,
 'standing': 142,
 'turned': 143,
 'one': 144,
 'side': 145,
 'boy': 146,
 'smiles': 147,
 'stony': 148,
 'wall': 149,
 'city': 150,
 'overalls': 151,
 'working': 152,
 'stone': 153,
 'aross': 154,
 'walking': 155,
 'paved': 156,
 'metal': 157,
 'pole': 158,
 'behind': 159,
 'smiling': 160,
 'shirt': 161,
 'blue': 162,
 'jeans': 163,
 'rock': 164,
 'leaps': 165,
 'over': 166,
 'log': 167,
 'grey': 168,
 'leaping': 169,
 'fallen': 170,
 'tree': 171,
 'mottled': 172,
 'collar': 173,
 'jumping': 174,
 'jumped': 175,
 'stump': 176,
 'snow': 177,
 'field': 178,
 'surface': 179,
 'displaying': 180,
 'pictures': 181,
 'skier': 182,
 'skis': 183,
 'past': 184,
 'another': 185,
 'paintings': 186,
 'person': 187,
 'framed': 188,
 'looks': 189,
 'trees': 190,
 'artwork': 191,
 'for': 192,
 'sale': 193,
 'collage': 194,
 'cliff': 195,
 'group': 196,
 'people': 197,
 'belays': 198,
 'seven': 199,
 'climbers': 200,
 'ascending': 201,
 'face': 202,
 'whilst': 203,
 'several': 204,
 'row': 205,
 'watches': 206,
 'holds': 207,
 'line': 208,
 'chases': 209,
 'from': 210,
 'sprinkler': 211,
 'lawn': 212,
 'hose': 213,
 'away': 214,
 'prepares': 215,
 'catch': 216,
 'thrown': 217,
 'object': 218,
 'nearby': 219,
 'cars': 220,
 'about': 221,
 'yellow': 222,
 'mouth': 223,
 'toy': 224,
 'ready': 225,
 'flying': 226,
 'air': 227,
 'after': 228,
 'get': 229,
 'jumps': 230,
 'towards': 231,
 'trying': 232,
 'midair': 233,
 'woman': 234,
 'waters': 235,
 'big': 236,
 'lake': 237,
 'lone': 238,
 'duck': 239,
 'swimming': 240,
 'around': 241,
 'watching': 242,
 'waves': 243,
 'hand': 244,
 'facing': 245,
 'skyline': 246,
 'couple': 247,
 'infant': 248,
 'being': 249,
 'held': 250,
 'male': 251,
 'pond': 252,
 'stroller': 253,
 'sit': 254,
 'baby': 255,
 'their': 256,
 'newborn': 257,
 'under': 258,
 'care': 259,
 'along': 260,
 'body': 261,
 'outdoors': 262,
 'surf': 263,
 'lab': 264,
 'tags': 265,
 'frolicks': 266,
 'splashes': 267,
 'this': 268,
 'splashing': 269,
 'drilling': 270,
 'hole': 271,
 'ice': 272,
 'frozen': 273,
 'men': 274,
 'fishing': 275,
 'play': 276,
 'making': 277,
 'turn': 278,
 'soft': 279,
 'sand': 280,
 'together': 281,
 'tan': 282,
 'sandy': 283,
 'uses': 284,
 'picks': 285,
 'crampons': 286,
 'scale': 287,
 'climber': 288,
 'jacket': 289,
 'pants': 290,
 'scaling': 291,
 'waterfall': 292,
 'carries': 293,
 'as': 294,
 'he': 295,
 'walks': 296,
 'carrying': 297,
 'has': 298,
 'item': 299,
 'wet': 300,
 'kayak': 301,
 'life': 302,
 'jackets': 303,
 'rowing': 304,
 'canoe': 305,
 'gentle': 306,
 'ride': 307,
 'courtyard': 308,
 'catching': 309,
 'snaps': 310,
 'lunges': 311,
 'chocolate': 312,
 'too': 313,
 'late': 314,
 'captures': 315,
 'driveway': 316,
 'stick': 317,
 'kneeling': 318,
 'goalie': 319,
 'hockey': 320,
 'guarding': 321,
 'goal': 322,
 'kid': 323,
 'rink': 324,
 'right': 325,
 'crouches': 326,
 'modern': 327,
 'art': 328,
 'structure': 329,
 'glass': 330,
 'reads': 331,
 'newspaper': 332,
 'sculpture': 333,
 'office': 334,
 'statue': 335,
 'backpack': 336,
 'buildings': 337,
 'reading': 338,
 'tent': 339,
 'enter': 340,
 'setting': 341,
 'hut': 342,
 'iced': 343,
 'tarp': 344,
 'snowy': 345,
 'three': 346,
 'hill': 347,
 'sky': 348,
 'them': 349,
 'stand': 350,
 'kneels': 351,
 'skyscraper': 352,
 'very': 353,
 'tall': 354,
 'distance': 355,
 'camera': 356,
 'bites': 357,
 'hard': 358,
 'treat': 359,
 'biting': 360,
 'baked': 361,
 'good': 362,
 'putting': 363,
 'both': 364,
 'eats': 365,
 'food': 366,
 'table': 367,
 'eating': 368,
 'pizza': 369,
 'tin': 370,
 'dish': 371,
 'mountainside': 372,
 'check': 373,
 'out': 374,
 'view': 375,
 'hilltop': 376,
 'overlooking': 377,
 'valley': 378,
 'hang': 379,
 'top': 380,
 'overlook': 381,
 'rest': 382,
 'ledge': 383,
 'above': 384,
 'moutains': 385,
 'down': 386,
 'many': 387,
 'inflatable': 388,
 'boats': 389,
 'kayakers': 390,
 'railing': 391,
 'rafts': 392,
 'below': 393,
 'crowd': 394,
 'jersey': 395,
 'pose': 396,
 'some': 397,
 'multiracial': 398,
 'posing': 399,
 'picture': 400,
 'asian': 401,
 'blond': 402,
 'background': 403,
 'guy': 404,
 'striped': 405,
 'takeout': 406,
 'television': 407,
 'floor': 408,
 'fast': 409,
 'meal': 410,
 'someone': 411,
 'tv': 412,
 'teens': 413,
 'rail': 414,
 'crowded': 415,
 'takes': 416,
 'jump': 417,
 'skateboard': 418,
 'performing': 419,
 'trick': 420,
 'leans': 421,
 'skateboarder': 422,
 'doing': 423,
 'board': 424,
 'platform': 425,
 'skateboarders': 426,
 'paddling': 427,
 'river': 428,
 'seen': 429,
 'kayaking': 430,
 'paddles': 431,
 'boat': 432,
 'paddle': 433,
 'shallow': 434,
 'girls': 435,
 'ocean': 436,
 'four': 437,
 'children': 438,
 'pajamas': 439,
 'have': 440,
 'pillow': 441,
 'fight': 442,
 'kids': 443,
 'bed': 444,
 'having': 445,
 'constructions': 446,
 'workers': 447,
 'beam': 448,
 'taking': 449,
 'break': 450,
 'construction': 451,
 'i': 452,
 'take': 453,
 'seat': 454,
 'steel': 455,
 'boys': 456,
 'puddle': 457,
 'balloon': 458,
 'mud': 459,
 'sunny': 460,
 'day': 461,
 'appears': 462,
 'wait': 463,
 'hailing': 464,
 'taxi': 465,
 'signaling': 466,
 'traffic': 467,
 'blonde': 468,
 'hair': 469,
 'tube': 470,
 'waving': 471,
 'arm': 472,
 'oncoming': 473,
 'brochure': 474,
 'train': 475,
 'rides': 476,
 'magizine': 477,
 'book': 478,
 'pamphlet': 479,
 'rocky': 480,
 'run': 481,
 'across': 482,
 'stones': 483,
 'area': 484,
 'descends': 485,
 'end': 486,
 'high': 487,
 'diving': 488,
 'pool': 489,
 'dive': 490,
 'window': 491,
 'overshirt': 492,
 'tank': 493,
 'chrome': 494,
 'door': 495,
 'puts': 496,
 'elevator': 497,
 'light': 498,
 'swim': 499,
 'shorts': 500,
 'trunks': 501,
 'arms': 502,
 'outstretched': 503,
 'hiker': 504,
 'bluff': 505,
 'mountains': 506,
 'ski': 507,
 's': 508,
 'landscape': 509,
 'mountain': 510,
 'beautiful': 511,
 'pauses': 512,
 'mountaintop': 513,
 'attempting': 514,
 'purple': 515,
 'low': 516,
 'cut': 517,
 'yard': 518,
 'frisbee': 519,
 'parking': 520,
 'lot': 521,
 'middle': 522,
 'during': 523,
 'heavy': 524,
 'mat': 525,
 'between': 526,
 'suv': 527,
 'pickup': 528,
 'open': 529,
 'busy': 530,
 'terrain': 531,
 'woolly': 532,
 'doberman': 533,
 'chasing': 534,
 'catches': 535,
 'tennis': 536,
 'multicolor': 537,
 'balloons': 538,
 'night': 539,
 'hot': 540,
 'lit': 541,
 'lined': 542,
 'nighttime': 543,
 'helmet': 544,
 'bike': 545,
 'miniature': 546,
 'dirt': 547,
 'bicycle': 548,
 'race': 549,
 'pedals': 550,
 'quickly': 551,
 'bmx': 552,
 'eight': 553,
 'gathered': 554,
 'dark': 555,
 'porch': 556,
 'darkened': 557,
 'room': 558,
 'throwing': 559,
 'cleans': 560,
 'bubbles': 561,
 'suds': 562,
 'wiped': 563,
 'clean': 564,
 'foam': 565,
 'ramp': 566,
 'soapy': 567,
 'getting': 568,
 'cleaned': 569,
 'slides': 570,
 'slide': 571,
 'wading': 572,
 'toys': 573,
 'floating': 574,
 'backyard': 575,
 'sliding': 576,
 'colorful': 577,
 'tubes': 578,
 'falling': 579,
 'wetsuit': 580,
 'toddler': 581,
 'waiting': 582,
 'come': 583,
 'so': 584,
 'droplets': 585,
 'fly': 586,
 'throws': 587,
 'sticks': 588,
 'tongue': 589,
 'make': 590,
 'faces': 591,
 'sticking': 592,
 'look': 593,
 'silly': 594,
 'horse': 595,
 'sweatshirt': 596,
 'fire': 597,
 'barrel': 598,
 'lead': 599,
 'horses': 600,
 'contained': 601,
 'bulldog': 602,
 'sheep': 603,
 'boxer': 604,
 'pushing': 605,
 'anouther': 606,
 'skinny': 607,
 'smaller': 608,
 'int': 609,
 'various': 610,
 'sizes': 611,
 'lady': 612,
 'no': 613,
 'dock': 614,
 'deck': 615,
 'closeup': 616,
 'that': 617,
 'paws': 618,
 'lying': 619,
 'resting': 620,
 'tiled': 621,
 'eyes': 622,
 'rests': 623,
 'patio': 624,
 'bricks': 625,
 'artificial': 626,
 'safety': 627,
 'harness': 628,
 'indoor': 629,
 'rocks': 630,
 'ring': 631,
 'jumphouse': 632,
 'teenage': 633,
 'seating': 634,
 'inflated': 635,
 'family': 636,
 'tractor': 637,
 'polaris': 638,
 'vehicle': 639,
 'played': 640,
 'wheeler': 641,
 'riding': 642,
 'atv': 643,
 'costume': 644,
 'left': 645,
 'sequined': 646,
 'feather': 647,
 'sidewalk': 648,
 'salmon': 649,
 'bikini': 650,
 'outfit': 651,
 'drinking': 652,
 'pop': 653,
 'approached': 654,
 'flamboyant': 655,
 'dressed': 656,
 'feathered': 657,
 'headress': 658,
 'skiiers': 659,
 'forest': 660,
 'skiing': 661,
 'wooded': 662,
 'cross': 663,
 'country': 664,
 'skiers': 665,
 'woodland': 666,
 'trail': 667,
 'woods': 668,
 'hikers': 669,
 'pathway': 670,
 'path': 671,
 'happily': 672,
 'energetic': 673,
 'mother': 674,
 'boardwalk': 675,
 'sea': 676,
 'pier': 677,
 'evening': 678,
 'pony': 679,
 'wintertime': 680,
 'atop': 681,
 'draft': 682,
 'n': 683,
 'daft': 684,
 'pull': 685,
 'cart': 686,
 'golden': 687,
 'sleigh': 688,
 'driven': 689,
 'coat': 690,
 'pulling': 691,
 'carriage': 692,
 'sled': 693,
 'steered': 694,
 'sheer': 695,
 'using': 696,
 'flat': 697,
 'rappels': 698,
 'steep': 699,
 'incline': 700,
 'vest': 701,
 'inside': 702,
 'dome': 703,
 'shaft': 704,
 'cave': 705,
 'shows': 706,
 'spelunkers': 707,
 'cavern': 708,
 'bathed': 709,
 'sunlight': 710,
 'backpackers': 711,
 'lay': 712,
 'dry': 713,
 'camp': 714,
 'gear': 715,
 'chalk': 716,
 'portrait': 717,
 'stream': 718,
 'drawing': 719,
 'barn': 720,
 'like': 721,
 'elaborate': 722,
 'illustration': 723,
 'deep': 724,
 'pile': 725,
 'fountain': 726,
 'fountains': 727,
 'sprayed': 728,
 'corgi': 729,
 'tunnel': 730,
 'course': 731,
 'obstacle': 732,
 'obedience': 733,
 'swimsuit': 734,
 'handrail': 735,
 'bathing': 736,
 'suit': 737,
 'spray': 738,
 'soaked': 739,
 'jet': 740,
 'shower': 741,
 'gets': 742,
 'underwater': 743,
 'headed': 744,
 'swims': 745,
 'gun': 746,
 'foot': 747,
 'aims': 748,
 'fireplace': 749,
 'new': 750,
 'pointed': 751,
 'alone': 752,
 'jagged': 753,
 'snowmobile': 754,
 'mid': 755,
 'snowmobiler': 756,
 'flies': 757,
 'rider': 758,
 'or': 759,
 'machine': 760,
 'pine': 761,
 'rural': 762,
 'snowmobiles': 763,
 'helmets': 764,
 'goggles': 765,
 'snowmobiling': 766,
 'helmeted': 767,
 'drive': 768,
 'atvs': 769,
 'heads': 770,
 'wheel': 771,
 'wheelers': 772,
 'empty': 773,
 'all': 774,
 'gin': 775,
 'airborne': 776,
 'quad': 777,
 'harvested': 778,
 'cornfield': 779,
 'happy': 780,
 'od': 781,
 'playfully': 782,
 'soccer': 783,
 'tucked': 784,
 't': 785,
 'artist': 786,
 'paints': 787,
 'clouds': 788,
 'braids': 789,
 'colors': 790,
 'paper': 791,
 'cyclist': 792,
 'curved': 793,
 'aerodynamic': 794,
 'sharp': 795,
 'curve': 796,
 'pedaling': 797,
 'cows': 798,
 'graze': 799,
 'biker': 800,
 'fetch': 801,
 'pounces': 802,
 'cine': 803,
 'old': 804,
 'fashioned': 805,
 'video': 806,
 'steadies': 807,
 'aim': 808,
 'rosy': 809,
 'cheeks': 810,
 'lips': 811,
 'border': 812,
 'collie': 813,
 'audience': 814,
 'dug': 815,
 'watch': 816,
 'agile': 817,
 'onlookers': 818,
 'closely': 819,
 'smooth': 820,
 'stacking': 821,
 'against': 822,
 'backdrop': 823,
 'shoes': 824,
 'rappeling': 825,
 'headlamp': 826,
 'attached': 827,
 'snakeskin': 828,
 'sprays': 829,
 'frog': 830,
 'public': 831,
 'wood': 832,
 'barrior': 833,
 'animal': 834,
 'bird': 835,
 'seeds': 836,
 'sunflower': 837,
 'clinging': 838,
 'finger': 839,
 'wades': 840,
 'guided': 841,
 'laughs': 842,
 'playful': 843,
 'beige': 844,
 'torwards': 845,
 'outdoor': 846,
 'handstand': 847,
 'does': 848,
 'sheets': 849,
 'upside': 850,
 'snowboard': 851,
 'surfboard': 852,
 'bikes': 853,
 'traveling': 854,
 'worn': 855,
 'motorcycles': 856,
 'motorbikes': 857,
 'follow': 858,
 'garment': 859,
 'flag': 860,
 'crescent': 861,
 'moon': 862,
 'star': 863,
 'gown': 864,
 'muslim': 865,
 'helps': 866,
 'wave': 867,
 'half': 868,
 'naked': 869,
 'chair': 870,
 'older': 871,
 'back': 872,
 'relaxes': 873,
 'adobe': 874,
 'where': 875,
 'bicycles': 876,
 'propped': 877,
 'cap': 878,
 'close': 879,
 'parked': 880,
 'relaxing': 881,
 'folding': 882,
 'topless': 883,
 'slippers': 884,
 'navy': 885,
 'reclining': 886,
 'hauling': 887,
 'retrieve': 888,
 'mouths': 889,
 'tug': 890,
 'chew': 891,
 'haired': 892,
 'bottled': 893,
 'drink': 894,
 'tilted': 895,
 'spiked': 896,
 'party': 897,
 'streets': 898,
 'they': 899,
 'women': 900,
 'parade': 901,
 'neck': 902,
 'vegetation': 903,
 'filled': 904,
 'bushes': 905,
 'creating': 906,
 'splash': 907,
 'seaweed': 908,
 'lav': 909,
 'swimmers': 910,
 'kelp': 911,
 'foreground': 912,
 'sandals': 913,
 'short': 914,
 'sleeved': 915,
 'pinstripe': 916,
 'snows': 917,
 'furry': 918,
 'attempts': 919,
 'itself': 920,
 'self': 921,
 'backpacks': 922,
 'placed': 923,
 'cardboard': 924,
 'bus': 925,
 'station': 926,
 'bouncing': 927,
 'folded': 928,
 'beds': 929,
 'bedroom': 930,
 'snowboarder': 931,
 'slope': 932,
 'boarders': 933,
 'snowboarders': 934,
 'slopes': 935,
 'clothing': 936,
 'store': 937,
 'opening': 938,
 'stores': 939,
 'piece': 940,
 'attire': 941,
 'car': 942,
 'strip': 943,
 'boots': 944,
 'stepping': 945,
 'van': 946,
 'wear': 947,
 'game': 948,
 'plants': 949,
 'crossing': 950,
 'greenery': 951,
 'suspension': 952,
 'tropical': 953,
 'caution': 954,
 'sign': 955,
 'beside': 956,
 'bright': 957,
 'truck': 958,
 'others': 959,
 'helping': 960,
 'step': 961,
 'pulled': 962,
 'passengers': 963,
 'load': 964,
 'brightly': 965,
 'poses': 966,
 'pig': 967,
 'hugs': 968,
 'who': 969,
 'embracing': 970,
 'event': 971,
 'hugging': 972,
 'hooded': 973,
 'stretch': 974,
 'bicyclist': 975,
 'spandex': 976,
 'biking': 977,
 'jogging': 978,
 'headset': 979,
 'walkman': 980,
 'jogs': 981,
 'headphones': 982,
 'plant': 983,
 'corner': 984,
 'bicyclists': 985,
 'intersection': 986,
 'bikers': 987,
 'stop': 988,
 'town': 989,
 'without': 990,
 'guiding': 991,
 'wagon': 992,
 'escorts': 993,
 'leading': 994,
 'drawn': 995,
 'shetland': 996,
 'hits': 997,
 'tee': 998,
 'practices': 999,
 ...}

In [25]:
def en_converter(x):
  return [en_vocab.get(word) for word in x]
def bn_converter(x):
  return [bn_vocab.get(word) for word in x]

In [26]:
df['en']=df["en"].apply(en_converter)
df["bn"]=df["bn"].apply(bn_converter)

In [27]:
df

,en,bn
0,"[1, 2, 3, 1, 4, 5, 6, 7, 8, 1, 9, 10, 11, 3, 1...","[3, 4, 5, 6, 7, 8, 3, 9, 10, 11, 12, 13, 14]"
1,"[1, 15, 16, 17, 1, 18, 19]","[3, 8, 15, 3, 16, 17, 18]"
2,"[1, 20, 15, 7, 17, 1, 18, 21]","[3, 7, 19, 16, 20, 14]"
3,"[1, 20, 15, 7, 22, 11, 23, 24, 21]","[21, 22, 19, 23, 24, 25, 13, 14]"
4,"[1, 20, 15, 3, 1, 4, 5, 16, 17, 1, 18, 25]","[26, 5, 27, 21, 3, 8, 3, 16, 28, 29, 10, 30]"
...,...,...
39060,"[1, 75, 3, 1, 4, 161, 112, 1, 164, 202]","[4, 2805, 3, 107, 3, 1066, 239, 5650]"
39061,"[1, 75, 6, 164, 7, 487, 3, 22, 227]","[92, 97, 702, 1325, 516, 239]"
39062,"[1, 187, 3, 1, 110, 161, 7, 8, 1, 164, 202, 54...","[140, 2805, 92, 103, 15657, 15658, 243, 3, 126..."
39063,"[1, 164, 288, 3, 1, 110, 161]","[140, 4049, 3, 1249, 288]"
39064,"[1, 164, 288, 999, 38, 1, 164, 7, 149]","[3, 1249, 288, 3, 5458, 144, 2685, 171, 91, 31..."

In [28]:
df["en"][0]

[1, 2, 3, 1, 4, 5, 6, 7, 8, 1, 9, 10, 11, 3, 12, 13, 14]

# Train Test Spliting

In [29]:
x_train, x_test, y_train, y_test = train_test_split(
    df["en"], df["bn"], test_size=0.2, random_state=42
)

# Padding

In [30]:
max_len = max(len(seq) for seq in x_train)
print(max_len)
max_len=max(len(seq) for seq in x_test)
print(max_len)

33
36

In [31]:
en_max_len=36

In [32]:
max_len=max( len(seq) for seq in y_train)
print(max_len)
max_len=max(len(seq) for seq in y_test)
print(max_len)

32
29

In [33]:
bn_max_len=32

In [34]:
from torch.nn.utils.rnn import pad_sequence

In [35]:
def padding(seq, actual_max_len):
  if len(seq) < actual_max_len:
    return seq + [0] * (actual_max_len - len(seq))
  else :
    return seq

In [36]:
x_train = [padding(seq, en_max_len) for seq in x_train]
x_test  = [padding(seq, en_max_len) for seq in x_test]

In [37]:
x_train[1]

[1,
 75,
 35,
 1,
 168,
 2061,
 6,
 62,
 80,
 1,
 491,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [38]:
y_train = [padding(seq, bn_max_len) for seq in y_train]
y_test  = [padding(seq, bn_max_len) for seq in y_test]

In [39]:
y_train[1]

[228,
 6110,
 3,
 107,
 722,
 168,
 72,
 389,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

# Dataset and Dataloader

In [40]:
class MDataset(Dataset):
  def __init__(self,feature,labels):
    self.feature=feature
    self.labels=labels
  def __len__(self):
    return len(self.feature)
  def __getitem__(self, index):
    x=torch.tensor(self.feature[index], dtype=torch.long)
    y=torch.tensor(self.labels[index], dtype=torch.long)
    return x,y

In [41]:
data=MDataset(x_train,y_train)

In [42]:
data

In [43]:
len(data)

31252

In [44]:
data_loader=DataLoader(data,num_workers=0,batch_size=128)

In [45]:
len(data_loader)

245

# Model creation

In [46]:
class Encoder(nn.Module):
  def __init__(self):
    super().__init__()
    self.emb=nn.Embedding(len(en_vocab),embedding_dim=50)
    self.lstm=nn.LSTM(50,hidden_size=128,batch_first=True)
  def forward(self,x):
    x=self.emb(x)
    output,(hidden,cell)=self.lstm(x)
    return output,hidden,cell

In [47]:
class Attention(nn.Module):
  def __init__(self):
    super().__init__()
  def forward(self,hidden,encoder_output):
    hidden=hidden.permute(1,2,0)
    score=torch.bmm(encoder_output,hidden).squeeze(2)
    weight=torch.softmax(score,dim=1)
    return weight

In [48]:
class Decoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.emb = nn.Embedding(len(bn_vocab), embedding_dim=50)
        self.attention = Attention()
        self.lstm = nn.LSTM(50 + 128, hidden_size=128, batch_first=True)
        #                    ↑    ↑
        #                  emb  hidden from attention context
        self.fc = nn.Linear(128, len(bn_vocab))

    def forward(self, target, hidden, cell, encoder_output):
        # target: (batch,) one word at a time

        # Step 1 — embed the input word
        target = target.unsqueeze(1)                          # (batch, 1)
        embedded = self.emb(target)                           # (batch, 1, 50)

        # Step 2 — attention
        weight = self.attention(hidden, encoder_output)       # (batch, src_len)
        weight = weight.unsqueeze(1)                          # (batch, 1, src_len)

        # Step 3 — context vector
        context = torch.bmm(weight, encoder_output)           # (batch, 1, 128)

        # Step 4 — concat embedding + context
        lstm_input = torch.cat([embedded, context], dim=2)   # (batch, 1, 50+128)

        # Step 5 — lstm
        output, (hidden, cell) = self.lstm(lstm_input, (hidden, cell))
        #                                               ↑
        #                                   pass hidden and cell forward

        # Step 6 — predict next word
        pred = self.fc(output.squeeze(1))                     # (batch, fr_vocab)

        return pred, hidden, cell

In [49]:
import random

In [60]:
class Seq2Seq(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = Encoder()
        self.decoder = Decoder()

    def forward(self, src, trg, teacher_forcing_ratio=0.5):
        # src: (batch, src_len)
        # trg: (batch, trg_len)

        batch_size = src.shape[0]
        trg_len    = trg.shape[1]

        # store predictions
        predictions = torch.zeros(batch_size, trg_len, len(bn_vocab)).to(src.device)

        # Step 1 — run encoder once
        encoder_output, hidden, cell = self.encoder(src)

        # Step 2 — first decoder input is <SOS> token
        input = trg[:, 0]                                      # (batch,)

        # Step 3 — decode word by word
        for t in range(1, trg_len):

            pred, hidden, cell = self.decoder(
                input, hidden, cell, encoder_output
            )
            predictions[:, t, :] = pred                        # store prediction

            # teacher forcing
            teacher_force = random.random() < teacher_forcing_ratio
            if teacher_force:
                input = trg[:, t]                              # use real word
            else:
                input = pred.argmax(1)                         # use predicted word

        return predictions

In [51]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [52]:
device

'cuda'

In [62]:
import random
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

# ── hyperparameters ──────────────────────────────
EPOCHS              = 10
BATCH_SIZE          = 32
LEARNING_RATE       = 0.01
TEACHER_FORCE_RATIO = 0.5
CLIP                = 1.0          # gradient clipping
pad_idx             = en_vocab['<oov>']

# ── model, optimizer, loss ───────────────────────
model     = Seq2Seq().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
criterion = nn.CrossEntropyLoss(ignore_index=pad_idx)
#                                ↑
#                   ignore PAD tokens in loss calculation

In [57]:
def train(model, dataloader, optimizer, criterion, clip):
    model.train()                          # set model to train mode
    epoch_loss = 0

    for src, trg in dataloader:
        if isinstance(src, list):
            src = torch.stack(src)         # Stack list of tensors into a single tensor
        src = src.to(device)               # (batch, src_len)

        if isinstance(trg, list):
            trg = torch.stack(trg)         # Stack list of tensors into a single tensor
        trg = trg.to(device)               # (batch, trg_len)

        # ── Step 1: clear gradients ──────────────
        optimizer.zero_grad()

        # ── Step 2: forward pass ─────────────────
        output = model(src, trg, TEACHER_FORCE_RATIO)
        # output: (batch, trg_len, vocab_size)

        # ── Step 3: reshape for loss ─────────────
        output = output[:, 1:, :].reshape(-1, len(bn_vocab))
        trg    = trg[:, 1:].reshape(-1)
        #              ↑
        #         skip <SOS> token

        # ── Step 4: calculate loss ───────────────
        loss = criterion(output, trg)

        # ── Step 5: backward pass ────────────────
        loss.backward()

        # ── Step 6: clip gradients ───────────────
        torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
        #                                                    ↑
        #                                       prevents exploding gradients

        # ── Step 7: update weights ───────────────
        optimizer.step()

        epoch_loss += loss.item()

    return epoch_loss / len(dataloader)    # average loss

In [58]:
def evaluate(model, dataloader, criterion):
    model.eval()                           # turn off dropout etc
    epoch_loss = 0

    with torch.no_grad():                  # no gradient calculation
        for src, trg in dataloader:
            if isinstance(src, list):
                src = torch.stack(src)     # Stack list of tensors into a single tensor
            src = src.to(device)

            if isinstance(trg, list):
                trg = torch.stack(trg)     # Stack list of tensors into a single tensor
            trg = trg.to(device)

            output = model(src, trg, teacher_forcing_ratio=0)
            #                                              ↑
            #                                no teacher forcing in eval

            output = output[:, 1:, :].reshape(-1, len(bn_vocab))
            trg    = trg[:, 1:].reshape(-1)

            loss = criterion(output, trg)
            epoch_loss += loss.item()

    return epoch_loss / len(dataloader)

In [63]:
best_loss = float('inf')

for epoch in range(EPOCHS):

    train_loss = train(model, data_loader, optimizer, criterion, CLIP)


    # save best model


    print(f"Epoch {epoch+1}/{EPOCHS}")
    print(f"  Train Loss: {train_loss:.4f}")

Epoch 1/10
  Train Loss: 6.8295
Epoch 2/10
  Train Loss: 6.2829
Epoch 3/10
  Train Loss: 5.8860
Epoch 4/10
  Train Loss: 5.5947
Epoch 5/10
  Train Loss: 5.3048
Epoch 6/10
  Train Loss: 5.1303
Epoch 7/10
  Train Loss: 4.9153
Epoch 8/10
  Train Loss: 4.7462
Epoch 9/10
  Train Loss: 4.5895
Epoch 10/10
  Train Loss: 4.4653

In [64]:
def preprocess_english_sentence(sentence, en_vocab, en_max_len):
    # Tokenize and convert to lowercase
    tokenized_sentence = tokenizing(sentence)
    # Convert words to numerical IDs
    numerical_sentence = en_converter(tokenized_sentence)
    # Pad the sequence
    padded_sentence = padding(numerical_sentence, en_max_len)
    return torch.tensor(padded_sentence, dtype=torch.long).unsqueeze(0).to(device) # Add batch dimension and move to device

In [65]:
def predict_bangla_sentence(model, english_sentence, en_vocab, bn_vocab, en_max_len, bn_max_len, device):
    model.eval() # Set model to evaluation mode

    # Preprocess the English input
    input_tensor = preprocess_english_sentence(english_sentence, en_vocab, en_max_len)

    # Encode the input sentence
    encoder_output, hidden, cell = model.encoder(input_tensor)

    # Prepare the first input to the decoder (SOS token)
    bn_itos = {v: k for k, v in bn_vocab.items()} # Invert bn_vocab for index to string conversion
    trg_indexes = [bn_vocab['<sos>']]
    input_decoder = torch.tensor([bn_vocab['<sos>']], dtype=torch.long).to(device) # Initial input is <sos>

    for _ in range(bn_max_len - 1): # Iterate up to max output length
        # Decode one word at a time
        output, hidden, cell = model.decoder(input_decoder, hidden, cell, encoder_output)

        # Get the predicted next word
        pred_token = output.argmax(1).item()
        trg_indexes.append(pred_token)

        # If EOS token is predicted, stop decoding
        if pred_token == bn_vocab['<eos>']:
            break

        # Use the predicted word as the next input to the decoder
        input_decoder = torch.tensor([pred_token], dtype=torch.long).to(device)

    # Convert numerical IDs back to words
    predicted_sentence = [bn_itos[idx] for idx in trg_indexes]

    # Remove <sos> and <eos> tokens for final output
    if predicted_sentence[0] == '<sos>':
        predicted_sentence = predicted_sentence[1:]
    if '<eos>' in predicted_sentence:
        predicted_sentence = predicted_sentence[:predicted_sentence.index('<eos>')]

    return ' '.join(predicted_sentence)

In [66]:
# Example usage:
english_sentence = "A man is drinking water."
predicted_bn = predict_bangla_sentence(model, english_sentence, en_vocab, bn_vocab, en_max_len, bn_max_len, device)
print(f"English: {english_sentence}")
print(f"Bangla: {predicted_bn}")

English: A man is drinking water.
Bangla: একটি একজন লোক দেখছে থেকে দিকে থেকে দিকে হচ্ছে করছে করছে করছে করছে দিকে তাকিয়ে আছে দেখছে করছে করছে থেকে দিকে চেষ্টা করছে থেকে দিকে চেষ্টা করছে থেকে দিকে চেষ্টা করছে