<a href="https://colab.research.google.com/github/SouravDasz/Deep-learning-projects-models-only-/blob/main/seqtoseq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [215]:
import numpy as np
import pandas as pd

In [216]:
df=pd.read_csv("/content/english_to_bangla (1).csv")

In [217]:
df.head()

,en,bn
0,a child in a pink dress is climbing up a set o...,একটি গোলাপী জামা পরা বাচ্চা মেয়ে একটি বাড়ির প্...
1,a girl going into a wooden building .,একটি মেয়ে শিশু একটি কাঠের বাড়িতে ঢুকছে
2,a little girl climbing into a wooden playhouse .,একটি বাচ্চা তার কাঠের খেলাঘরে উঠছে ।
3,a little girl climbing the stairs to her playh...,ছোট মেয়েটি তার খেলার ঘরের সিড়ি বেয়ে উঠছে
4,a little girl in a pink dress going into a woo...,গোলাপি জামা পড়া ছোট একটি মেয়ে একটি কাঠের তৈরি...

In [218]:
df.shape

(39065, 2)

In [219]:
df["en"][2]

'a little girl climbing into a wooden playhouse .'

In [220]:
import re
def process(x):
  x=x.lower()
  x=x.split(" ")
  # Removed x=x[:-1] as it incorrectly removed the last word
  return x

In [221]:
df["en"]=df["en"].apply(process)

In [222]:
df

,en,bn
0,"[a, child, in, a, pink, dress, is, climbing, u...",একটি গোলাপী জামা পরা বাচ্চা মেয়ে একটি বাড়ির প্...
1,"[a, girl, going, into, a, wooden, building, .]",একটি মেয়ে শিশু একটি কাঠের বাড়িতে ঢুকছে
2,"[a, little, girl, climbing, into, a, wooden, p...",একটি বাচ্চা তার কাঠের খেলাঘরে উঠছে ।
3,"[a, little, girl, climbing, the, stairs, to, h...",ছোট মেয়েটি তার খেলার ঘরের সিড়ি বেয়ে উঠছে
4,"[a, little, girl, in, a, pink, dress, going, i...",গোলাপি জামা পড়া ছোট একটি মেয়ে একটি কাঠের তৈরি...
...,...,...
39060,"[a, man, in, a, pink, shirt, climbs, a, rock, ...",গোলাপী শার্টের একটি লোক একটি শিলার উপরে উঠেছিল
39061,"[a, man, is, rock, climbing, high, in, the, ai...",একজন মানুষ পাথরে চড়ছে অনেক উপরে
39062,"[a, person, in, a, red, shirt, climbing, up, a...",লাল শার্টের একজন ব্যক্তি সহায়তার হাতলগুলিতে ঢ...
39063,"[a, rock, climber, in, a, red, shirt, .]",লাল শার্টে একটি রক আরোহী
39064,"[a, rock, climber, practices, on, a, rock, cli...",একটি রক আরোহী একটি শৈল আরোহণ প্রাচীর এর উপর অন...

In [223]:
df.tail()

,en,bn
39060,"[a, man, in, a, pink, shirt, climbs, a, rock, ...",গোলাপী শার্টের একটি লোক একটি শিলার উপরে উঠেছিল
39061,"[a, man, is, rock, climbing, high, in, the, ai...",একজন মানুষ পাথরে চড়ছে অনেক উপরে
39062,"[a, person, in, a, red, shirt, climbing, up, a...",লাল শার্টের একজন ব্যক্তি সহায়তার হাতলগুলিতে ঢ...
39063,"[a, rock, climber, in, a, red, shirt, .]",লাল শার্টে একটি রক আরোহী
39064,"[a, rock, climber, practices, on, a, rock, cli...",একটি রক আরোহী একটি শৈল আরোহণ প্রাচীর এর উপর অন...

In [224]:
df["bn"]=df["bn"].apply(process)

In [225]:
df.head()

,en,bn
0,"[a, child, in, a, pink, dress, is, climbing, u...","[একটি, গোলাপী, জামা, পরা, বাচ্চা, মেয়ে, একটি, ..."
1,"[a, girl, going, into, a, wooden, building, .]","[একটি, মেয়ে, শিশু, একটি, কাঠের, বাড়িতে, ঢুকছে]"
2,"[a, little, girl, climbing, into, a, wooden, p...","[একটি, বাচ্চা, তার, কাঠের, খেলাঘরে, উঠছে, ।]"
3,"[a, little, girl, climbing, the, stairs, to, h...","[ছোট, মেয়েটি, তার, খেলার, ঘরের, সিড়ি, বেয়ে, উঠছে]"
4,"[a, little, girl, in, a, pink, dress, going, i...","[গোলাপি, জামা, পড়া, ছোট, একটি, মেয়ে, একটি, কা..."

In [226]:
from collections import Counter

In [214]:
en_counter=Counter()
bn_counter=Counter()

In [227]:
for seq in df["en"]:
  en_counter.update(seq)

In [228]:
len(en_counter)

8831

In [ ]:
for seq in df["bn"]:
  bn_counter.update(seq)

In [230]:
len(bn_counter)

17347

In [231]:
en_vocab={
    "<pad>":0,
    "<unk>":1
}

In [232]:
bn_vocab={
    "<pad>":0,
    "<unk>":1,
    "<sos>":2,
    "<eos>":3
}

In [233]:
for word,value in en_counter.items():
  if word not in en_vocab:
    en_vocab[word]=len(en_vocab)

In [234]:
len(en_vocab)

8833

In [235]:
for word ,value in bn_counter.items():
  if word not in bn_vocab:
    bn_vocab[word]=len(bn_vocab)

In [236]:
device="cuda"  if torch.cuda.is_available() else "cpu"

In [237]:
len(bn_vocab)

17351

In [238]:
en_len=[]
for seq in df["en"]:
  en_len.append(len(seq))
print(max(en_len))

38

In [239]:
bn_len=[]
for seq in df["bn"]:
  bn_len.append(len(seq))
print(max(bn_len))

32

In [240]:
def integer_encoding(text):
  text=[en_vocab.get(word,en_vocab["<unk>"]) for word in text]
  if len(text)<37:
    text=text+[en_vocab["<pad>"]]*(37-len(text))
  else:
    text=text[:37]
  return text

In [241]:
df["en"]=df['en'].apply(integer_encoding)

In [242]:
df

,en,bn
0,"[2, 3, 4, 2, 5, 6, 7, 8, 9, 2, 10, 11, 12, 4, ...","[একটি, গোলাপী, জামা, পরা, বাচ্চা, মেয়ে, একটি, ..."
1,"[2, 17, 18, 19, 2, 20, 21, 16, 0, 0, 0, 0, 0, ...","[একটি, মেয়ে, শিশু, একটি, কাঠের, বাড়িতে, ঢুকছে]"
2,"[2, 22, 17, 8, 19, 2, 20, 23, 16, 0, 0, 0, 0, ...","[একটি, বাচ্চা, তার, কাঠের, খেলাঘরে, উঠছে, ।]"
3,"[2, 22, 17, 8, 24, 12, 25, 26, 23, 16, 0, 0, 0...","[ছোট, মেয়েটি, তার, খেলার, ঘরের, সিড়ি, বেয়ে, উঠছে]"
4,"[2, 22, 17, 4, 2, 5, 6, 18, 19, 2, 20, 27, 16,...","[গোলাপি, জামা, পড়া, ছোট, একটি, মেয়ে, একটি, কা..."
...,...,...
39060,"[2, 76, 4, 2, 5, 163, 113, 2, 166, 204, 0, 0, ...","[গোলাপী, শার্টের, একটি, লোক, একটি, শিলার, উপরে..."
39061,"[2, 76, 7, 166, 8, 490, 4, 24, 229, 16, 0, 0, ...","[একজন, মানুষ, পাথরে, চড়ছে, অনেক, উপরে]"
39062,"[2, 189, 4, 2, 111, 163, 8, 9, 2, 166, 204, 55...","[লাল, শার্টের, একজন, ব্যক্তি, সহায়তার, হাতলগু..."
39063,"[2, 166, 290, 4, 2, 111, 163, 16, 0, 0, 0, 0, ...","[লাল, শার্টে, একটি, রক, আরোহী]"
39064,"[2, 166, 290, 1011, 39, 2, 166, 8, 151, 16, 0,...","[একটি, রক, আরোহী, একটি, শৈল, আরোহণ, প্রাচীর, এ..."

In [243]:
def integer_encoding(text):
  # Get integer IDs for words
  encoded_words = [bn_vocab.get(word, bn_vocab["<unk>"]) for word in text]

  # Add <sos> and <eos> tokens
  # The sequence will be <sos>, actual_words, <eos>
  # This makes the length 2 + len(actual_words)
  seq_with_special_tokens = [bn_vocab["<sos>"]] + encoded_words + [bn_vocab["<eos>"]]

  # Handle padding or truncation to the maximum length (31)
  if len(seq_with_special_tokens) < 31:
    # Pad if shorter than max length
    seq_with_special_tokens = seq_with_special_tokens + [bn_vocab["<pad>"]] * (31 - len(seq_with_special_tokens))
  else:
    # Truncate if longer than max length. Ensure <sos> is kept, and <eos> is kept if possible.
    # So, truncate the 'encoded_words' part to make space for <sos> and <eos>
    truncated_encoded_words = encoded_words[:31 - 2] # leave space for <sos> and <eos>
    seq_with_special_tokens = [bn_vocab["<sos>"]] + truncated_encoded_words + [bn_vocab["<eos>"]]

  return seq_with_special_tokens

In [244]:
df["bn"]=df["bn"].apply(integer_encoding)

In [245]:
df

,en,bn
0,"[2, 3, 4, 2, 5, 6, 7, 8, 9, 2, 10, 11, 12, 4, ...","[2, 4, 5, 6, 7, 8, 9, 4, 10, 11, 12, 13, 14, 1..."
1,"[2, 17, 18, 19, 2, 20, 21, 16, 0, 0, 0, 0, 0, ...","[2, 4, 9, 16, 4, 17, 18, 19, 3, 0, 0, 0, 0, 0,..."
2,"[2, 22, 17, 8, 19, 2, 20, 23, 16, 0, 0, 0, 0, ...","[2, 4, 8, 20, 17, 21, 22, 23, 3, 0, 0, 0, 0, 0..."
3,"[2, 22, 17, 8, 24, 12, 25, 26, 23, 16, 0, 0, 0...","[2, 24, 25, 20, 26, 27, 28, 14, 22, 3, 0, 0, 0..."
4,"[2, 22, 17, 4, 2, 5, 6, 18, 19, 2, 20, 27, 16,...","[2, 29, 6, 30, 24, 4, 9, 4, 17, 31, 32, 11, 33..."
...,...,...
39060,"[2, 76, 4, 2, 5, 163, 113, 2, 166, 204, 0, 0, ...","[2, 5, 2994, 4, 112, 4, 1123, 255, 7868, 3, 0,..."
39061,"[2, 76, 7, 166, 8, 490, 4, 24, 229, 16, 0, 0, ...","[2, 97, 102, 736, 1400, 541, 255, 3, 0, 0, 0, ..."
39062,"[2, 189, 4, 2, 111, 163, 8, 9, 2, 166, 204, 55...","[2, 147, 2994, 97, 108, 17349, 17350, 259, 4, ..."
39063,"[2, 166, 290, 4, 2, 111, 163, 16, 0, 0, 0, 0, ...","[2, 147, 4336, 4, 1319, 305, 3, 0, 0, 0, 0, 0,..."
39064,"[2, 166, 290, 1011, 39, 2, 166, 8, 151, 16, 0,...","[2, 4, 1319, 305, 4, 5873, 151, 2865, 180, 96,..."

In [246]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset,DataLoader

In [247]:
class Custom_Dataset(Dataset):
  def __init__(self,df):
    self.df=df
  def __len__(self):
    return self.df.shape[0]
  def __getitem__(self,idx):
    text=torch.tensor(self.df["en"][idx], dtype=torch.long)
    label=torch.tensor(self.df['bn'][idx], dtype=torch.long)

    return text,label

In [248]:
data=Custom_Dataset(df)

In [249]:
data_loader=DataLoader(data,batch_size=32,shuffle=True)

In [250]:
# Encoder

class Encoder(nn.Module):
  def __init__(self,emb_size,hidden_size):
    super().__init__()
    self.emb=nn.Embedding(len(en_vocab),embedding_dim=emb_size)
    self.lstm=nn.LSTM(input_size=128,hidden_size=hidden_size,batch_first=True)


  def forward(self,x):
    out=self.emb(x)
    out,(ht,ct)=self.lstm(out)
    return ht,ct

In [251]:
# Decoder

class Deocder(nn.Module):
  def __init__(self,emb_size,hidden_size):
    super().__init__()
    self.emb=nn.Embedding(len(bn_vocab),embedding_dim=emb_size)
    self.lstm=nn.LSTM(input_size=emb_size,hidden_size=hidden_size,batch_first=True)
    self.linear=nn.Linear(hidden_size,len(bn_vocab))

  def forward(self,x,ht,ct):
    x=x.unsqueeze(1)
    out=self.emb(x)
    out,(ht,ct)=self.lstm(out,(ht,ct))
    output=out.squeeze(1)
    prediction=self.linear(output)
    return prediction,ht,ct

In [252]:
# seq to seq

class Seq2Seq(nn.Module):
  def __init__(self,encoder,decoder):
    super().__init__()
    self.encoder=encoder
    self.decoder=decoder
  def forward(self,x,y):
    batch=y.shape[0]
    seq_len=y.shape[1]
    prediction=torch.zeros(batch,seq_len,len(bn_vocab)).to(x.device)

    ht,ct=self.encoder(x)
    input=y[:,0]
    for t in range(1,seq_len):
      output,ht,ct=self.decoder(input,ht,ct)
      prediction[:,t,:]=output
      input=y[:,t]
    return prediction

In [253]:
emb_size=128
hidden_dim=128
encoder=Encoder(emb_size=emb_size,hidden_size=hidden_dim)
decoder=Deocder(emb_size=emb_size,hidden_size=hidden_dim)
model=Seq2Seq(encoder,decoder)
model.to(device)

Seq2Seq(
  (encoder): Encoder(
    (emb): Embedding(8833, 128)
    (lstm): LSTM(128, 128, batch_first=True)
  )
  (decoder): Deocder(
    (emb): Embedding(17351, 128)
    (lstm): LSTM(128, 128, batch_first=True)
    (linear): Linear(in_features=128, out_features=17351, bias=True)
  )
)

In [254]:
critrion=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters(),lr=0.001)

In [255]:
for input,label in data_loader :
  print(input)
  break

tensor([[  2,  76,   7,  ...,   0,   0,   0],
        [  2, 236,   4,  ...,   0,   0,   0],
        [ 71,   7,  13,  ...,   0,   0,   0],
        ...,
        [  2,  74, 148,  ...,   0,   0,   0],
        [  2,  76,  30,  ...,   0,   0,   0],
        [ 47, 276,   4,  ...,   0,   0,   0]])

In [ ]:
for epochs in range(15):
  epochs_loss=0
  correct=0
  total=0
  model.train()
  for input,label in data_loader:
    optimizer.zero_grad()

    input=input.to(device)
    label=label.to(device)
    prediction=model(input,label)
    # print(prediction.shape) # Commented out print statement to avoid excessive output during training
    pred=prediction
    output=pred[:,1:,:].reshape(-1, len(bn_vocab))
    target=label[:,1:].reshape(-1)

    loss=critrion(output,target)
    loss.backward()
    optimizer.step()
    epochs_loss+=loss.item()
    pred_clss=torch.argmax(output,dim=-1)
    correct+=(pred_clss==target).sum().item()
    total+=len(target)
  print(epochs_loss,f"and acc is f{correct/total}")

2347.8362551927567 and acc is f0.7383079482913093
1891.22481071949 and acc is f0.7618490549938137
1741.661369919777 and acc is f0.7695174708818635
1608.9259940385818 and acc is f0.7780801228721362
1487.8847071528435 and acc is f0.7867332224070993
1384.2179617881775 and acc is f0.7939468407355262
1294.3189777731895 and acc is f0.8002244123042792
1216.4602869153023 and acc is f0.8059951363112761
1148.7649936676025 and acc is f0.8117010111352874

In [ ]:
def prediction(model, bn_vocab, text, device):
    model.eval()

    with torch.no_grad():
        text = process(text)
        text = integer_encoding(text)

        text = torch.tensor(text).unsqueeze(0).to(device)

        ht, ct = model.encoder(text)

        input = torch.tensor([bn_vocab["<sos>"]]).to(device)

        outputs = []

        for t in range(31):
            output, ht, ct = model.decoder(input, ht, ct)

            pred_clss = torch.argmax(output, dim=-1)
            token_id = pred_clss.item()

            outputs.append(token_id)

            if token_id == bn_vocab["<eos>"]:
                break

            input = pred_clss

    return outputs